import { Course, CourseModule } from '@/types';

export const COURSE_ANALOG: Course = {
  id: 'c-analog-001',
  title: 'Analog Electronic Circuits',
  slug: 'analog-electronic-circuits',
  description: 'A comprehensive, rigorous course covering fundamental analog electronic devices, biasing topologies, small-signal models, operational amplifiers, active filters, feedback systems, oscillators, and power stages.',
  level: 'Undergraduate / Professional',
  estimated_hours: 48,
  thumbnail_url: '/images/analog-circuits.jpg',
  status: 'PUBLISHED',
  created_at: '2026-01-15T00:00:00Z',
  updated_at: '2026-09-29T12:00:00Z',
};

export const MODULES_ANALOG: CourseModule[] = [
  {
    id: 'mod-01',
    course_id: 'c-analog-001',
    title: 'Introduction to Analog Electronics',
    slug: 'introduction-to-analog-electronics',
    description: 'Fundamental signals, continuous vs discrete domains, analog system blocks, noise considerations, and basic linear circuit analysis.',
    order_number: 1,
    estimated_minutes: 40,
    content: {
      learning_objectives: [
        'Differentiate between continuous-time analog signals and discrete digital representations',
        'Analyze signal-to-noise ratio (SNR), dynamic range, and harmonic distortion in analog paths',
        'Apply Thevenin, Norton, and superposition theorems to loaded analog ports',
        'Understand impedance matching criteria for maximum power transfer vs maximum voltage transfer'
      ],
      theory: [
        'Analog electronics governs physical signals in the continuous domain. Real-world phenomena such as temperature, pressure, sound waves, and electromagnetic radiation are fundamentally continuous. Analog signal chains condition these signals using amplification, filtering, and impedance transformation prior to digitization.',
        'Unlike digital circuits that quantize signals into discrete states (0 and 1) subject to binary noise margins, analog circuits must preserve the precise instantaneous amplitude, phase, and spectral purity. This makes analog design sensitive to component tolerances, thermal drift, parasitic capacitance, and intrinsic device noise.',
        'Thermal noise (Johnson-Nyquist noise) sets the fundamental theoretical lower limit for detectable signal power in resistive networks: Pn = 4 * k * T * B.'
      ],
      circuit_description: 'Block diagram of a high-fidelity analog frontend showing sensor transducer, preamplifier, bandpass anti-aliasing filter, and buffer stage.',
      working_principle: [
        '1. Transducer converts physical stimulus into an infinitesimal voltage or current signal.',
        '2. Low-noise preamplifier provides immediate voltage gain while minimizing noise figure contribution according to Friis formula.',
        '3. Active continuous-time filter restricts signal bandwidth to the Nyquist zone, attenuating out-of-band interference.',
        '4. Buffer stage lowers source impedance to drive transmission line or sampling capacitive load.'
      ],
      equations: [
        {
          title: 'Johnson-Nyquist Thermal Noise Voltage',
          formula: 'V_n = \\sqrt{4 \\cdot k_B \\cdot T \\cdot R \\cdot \\Delta f}',
          description: 'Where kB is Boltzmann constant (1.38e-23 J/K), T is temperature in Kelvin, R is resistance in ohms, and delta f is noise bandwidth in Hertz.'
        },
        {
          title: 'Signal-to-Noise Ratio (dB)',
          formula: 'SNR_{dB} = 10 \\cdot \\log_{10}\\left(\\frac{P_{signal}}{P_{noise}}\\right) = 20 \\cdot \\log_{10}\\left(\\frac{V_{signal,rms}}{V_{noise,rms}}\\right)',
          description: 'Logarithmic ratio comparing desired electrical signal magnitude to background stochastic noise floor.'
        },
        {
          title: 'Maximum Power Transfer Theorem',
          formula: 'Z_L = Z_S^* \\quad \\text{for complex AC}, \\quad R_L = R_S \\quad \\text{for DC}',
          description: 'Maximum power is transferred from source to load when load impedance matches the complex conjugate of source impedance.'
        }
      ],
      characteristics: [
        {
          title: 'Key Analog Performance Metrics',
          points: [
            'Dynamic Range (DR): Ratio between maximum undistorted signal level and minimum detectable signal above noise floor',
            'Total Harmonic Distortion (THD): Measure of non-linear harmonic distortion generated by non-ideal active elements',
            'Bandwidth (-3dB): Frequency span where voltage gain remains within 70.7% of passband value'
          ]
        }
      ],
      applications: [
        'Biomedical instrumentation (ECG/EEG bio-potential amplifiers)',
        'RF receivers and microwave front-ends',
        'Audio mixing consoles and high-fidelity preamplifiers',
        'Precision sensor measurement systems in aerospace and automotive'
      ],
      advantages: [
        'Infinite theoretical resolution within noise constraints',
        'Instantaneous real-time processing without clock latency or quantization delay',
        'Simple low-power implementations for basic filtering and amplification'
      ],
      limitations: [
        'Vulnerability to thermal drift, aging, and component manufacturing tolerances',
        'Susceptibility to electromagnetic interference (EMI) and power rail crosstalk',
        'Difficult to automate synthesis and layout compared to digital logic'
      ],
      practical_notes: [
        'Always design ground planes continuously without splits underneath high-impedance analog traces.',
        'Use ceramic decoupling capacitors (100nF X7R) placed directly adjacent to IC power pins to suppress rail resonance.'
      ]
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  },
  {
    id: 'mod-02',
    course_id: 'c-analog-001',
    title: 'Semiconductor Fundamentals',
    slug: 'semiconductor-fundamentals',
    description: 'Energy band theory, intrinsic and extrinsic semiconductors, drift and diffusion transport mechanisms, and Fermi-Dirac statistics.',
    order_number: 2,
    estimated_minutes: 50,
    content: {
      learning_objectives: [
        'Analyze energy band diagrams, bandgap energy (Eg), and valence/conduction bands in silicon and GaAs',
        'Calculate carrier concentrations (n, p) using mass-action law and Fermi level position',
        'Differentiate between carrier drift under electric fields and diffusion driven by concentration gradients',
        'Understand Einstein relation linking mobility (mu) and diffusion coefficient (D)'
      ],
      theory: [
        'Semiconductors possess an electrical conductivity intermediate between conductors and insulators, typically governed by an energy bandgap Eg around 1.12 eV for crystalline Silicon at 300K.',
        'Pure intrinsic silicon has an equal concentration of electrons (ni) and holes (pi). By introducing trivalent impurity atoms (e.g. Boron), p-type semiconductors with dominant hole concentrations are formed. Introducing pentavalent impurities (e.g. Phosphorus, Arsenic) yields n-type material with excess mobile conduction electrons.',
        'Current transport occurs via two distinct mechanisms: drift current produced by electrostatic Lorentz forces, and diffusion current arising from spatial gradients in carrier densities.'
      ],
      circuit_description: 'Semiconductor crystal lattice and energy band diagram showing donor/acceptor levels relative to valence (Ev) and conduction (Ec) band edges.',
      working_principle: [
        '1. Doping increases majority carrier density while suppressing minority carriers according to mass action law (n * p = ni^2).',
        '2. Applied electric field E imparts net drift velocity v_d = mu * E until lattice scattering saturates.',
        '3. Non-uniform carrier distribution causes carriers to diffuse from regions of high concentration to low concentration.',
        '4. Total current density J is the vector sum of electron drift, electron diffusion, hole drift, and hole diffusion.'
      ],
      equations: [
        {
          title: 'Mass-Action Law',
          formula: 'n \\cdot p = n_i^2(T) = N_c N_v \\exp\\left(-\\frac{E_g}{k_B T}\\right)',
          description: 'Under thermal equilibrium, the product of electron and hole concentrations is invariant for a given semiconductor at temperature T.'
        },
        {
          title: 'Total Current Density (Drift + Diffusion)',
          formula: 'J_{total} = q (n \\mu_n + p \\mu_p) E + q D_n \\frac{dn}{dx} - q D_p \\frac{dp}{dx}',
          description: 'Combined equation for conduction current in one dimension incorporating electron and hole dynamics.'
        },
        {
          title: 'Einstein Relation',
          formula: '\\frac{D_n}{\\mu_n} = \\frac{D_p}{\\mu_p} = \\frac{k_B T}{q} = V_T \\approx 25.9\\,\\text{mV at } 300\\text{K}',
          description: 'Fundamental relationship tying carrier diffusivity to electric field mobility via the thermal voltage VT.'
        }
      ],
      characteristics: [
        {
          title: 'Carrier Dynamics',
          points: [
            'Mobility temperature coefficient: Mobility decreases at elevated temperatures due to acoustic phonon scattering',
            'Velocity saturation: At high electric fields (>10^4 V/cm in Si), carrier velocity saturates near 1e7 cm/s',
            'Resistivity: rho = 1 / (q * (n * mu_n + p * mu_p))'
          ]
        }
      ],
      applications: [
        'Substrate engineering for CMOS integrated circuits',
        'Photovoltaic cells and photodiodes',
        'Thermoelectric cooling devices and Peltier junctions',
        'Semiconductor radiation detectors'
      ],
      advantages: [
        'Conductivity modifiable over 8 orders of magnitude via ion implantation',
        'Silicon naturally forms a durable, high-breakdown native oxide (SiO2)',
        'Abundant raw material with mature high-yield fabrication ecosystems'
      ],
      limitations: [
        'Thermal leakage escalates exponentially with temperature due to ni(T) growth',
        'Susceptible to radiation damage (latch-up, single-event upsets)',
        'Carrier mobility in Si is lower than in III-V compound semiconductors (GaAs, InP)'
      ],
      practical_notes: [
        'Always account for temperature variations when computing bias drift; VT increases by ~86 microvolts per Kelvin.',
        'Silicon bandgap narrows at approximately -0.473 meV/K as temperature rises.'
      ]
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  },
  {
    id: 'mod-03',
    course_id: 'c-analog-001',
    title: 'PN Junction Diode',
    slug: 'pn-junction-diode',
    description: 'Depletion region formation, built-in potential, Shockley diode equation, forward and reverse bias characteristics, and junction capacitances.',
    order_number: 3,
    estimated_minutes: 55,
    content: {
      learning_objectives: [
        'Understand space charge region formation, built-in contact potential V0, and electric field profile',
        'Apply the Shockley diode equation under forward and reverse bias conditions',
        'Analyze temperature dependence of diode forward voltage (-2 mV/°C coefficient)',
        'Evaluate junction depletion capacitance (Cj) and diffusion capacitance (Cd) under AC operation'
      ],
      theory: [
        'When p-type and n-type semiconductor regions are brought into metallurgical contact, mobile holes and electrons diffuse across the junction, recombining and leaving uncompensated fixed ionized dopant cores (acceptor ions in p, donor ions in n).',
        'This unneutralized zone forms the depletion or space-charge region, creating a built-in electric field that opposes further majority carrier diffusion until dynamic equilibrium is reached.',
        'Under forward bias (positive potential on p-anode relative to n-cathode), the external voltage reduces the potential barrier, permitting exponential majority carrier injection. Under reverse bias, the barrier height increases, reducing current to the tiny reverse saturation current Is.'
      ],
      circuit_description: 'PN junction diode schematic symbol with anode and cathode, depletion region width under bias, and characteristic I-V curve.',
      working_principle: [
        '1. Zero Bias: Diffusion current equals drift current in magnitude; net terminal current is strictly zero.',
        '2. Forward Bias: External voltage V reduces barrier (V0 - V), enabling diffusion current to grow exponentially: I = Is * (exp(V / (eta*VT)) - 1).',
        '3. Reverse Bias: External potential widens depletion layer; only thermally generated minority carriers contribute to Is.',
        '4. Breakdown: At high reverse electric fields, avalanche impact ionization or Zener quantum tunneling occurs.'
      ],
      equations: [
        {
          title: 'Shockley Diode Equation',
          formula: 'I = I_s \\left( e^{\\frac{V}{\\eta V_T}} - 1 \\right)',
          description: 'Where Is is reverse saturation current (typically 1e-15 to 1e-12 A for Si), eta is ideality factor (1 to 2), and VT is thermal voltage.'
        },
        {
          title: 'Built-in Potential',
          formula: 'V_0 = V_T \\ln\\left( \\frac{N_A N_D}{n_i^2} \\right)',
          description: 'Built-in barrier voltage created by ionized dopants in thermal equilibrium without external bias.'
        },
        {
          title: 'Small-Signal Diode Resistance (Dynamic Resistance)',
          formula: 'r_d = \\frac{d V}{d I} \\approx \\frac{\\eta V_T}{I_D}',
          description: 'Incremental dynamic resistance of the diode evaluated at its DC quiescent operating point ID.'
        }
      ],
      characteristics: [
        {
          title: 'I-V Curve Behavior',
          points: [
            'Cut-in / Knee Voltage (V_gamma): ~0.65V to 0.7V for Silicon, ~0.2V to 0.3V for Germanium, ~0.35V for Schottky',
            'Temperature sensitivity: Forward drop decreases by approximately 2 mV per degree Celsius rise at constant forward current',
            'Reverse recovery time (trr): Latency required to sweep out minority carriers stored during forward conduction'
          ]
        }
      ],
      applications: [
        'AC-to-DC rectification and peak detection',
        'Over-voltage clamping and electrostatic discharge (ESD) protection',
        'Flyback snubber diodes across inductive coils and relay windings',
        'Signal demodulation in AM radio receivers'
      ],
      advantages: [
        'Simple, passive two-terminal unidirectional electronic switch',
        'Extremely fast response in fast-recovery and Schottky variants',
        'Low forward conduction loss in modern trench Schottky designs'
      ],
      limitations: [
        'Forward voltage drop causes thermal dissipation at high currents (P = VF * I)',
        'Reverse recovery charge introduces high-frequency switching noise (EMI)',
        'Reverse breakdown current can destroy device without external ballasting resistor'
      ],
      practical_notes: [
        'When selecting freewheeling diodes for inductive loads, ensure peak inverse voltage (PIV) rating exceeds 2x supply rail.',
        'Silicon 1N4148 is ideal for high-speed small-signal switching, whereas 1N4007 is suitable for 50/60 Hz power rectification.'
      ]
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  },
  {
    id: 'mod-04',
    course_id: 'c-analog-001',
    title: 'Rectifiers and Filters',
    slug: 'rectifiers-and-filters',
    description: 'Half-wave, full-wave center-tapped, and bridge rectifiers; ripple factor, rectification efficiency, transformer utilization factor, and capacitive/LC smoothing filters.',
    order_number: 4,
    estimated_minutes: 60,
    content: {
      learning_objectives: [
        'Derive DC output voltage, RMS voltage, and ripple factor (gamma) for half-wave and full-wave topologies',
        'Compare Peak Inverse Voltage (PIV) requirements between center-tapped and bridge rectifiers',
        'Calculate ripple voltage and conduction angle for shunt capacitor smoothing filters',
        'Design LC and Pi-section filter networks for high ripple attenuation'
      ],
      theory: [
        'Rectification is the conversion of bidirectional alternating current (AC) into pulsating unidirectional direct current (DC). Power supply front-ends use transformer secondary windings coupled to diode arrangements to produce half-wave or full-wave rectified waveforms.',
        'Full-wave bridge rectifiers utilize four diodes in a closed ring matrix, utilizing both positive and negative AC half-cycles without requiring a bulky, expensive center-tapped secondary winding.',
        'Pulsating DC contains a large AC harmonic ripple component. Low-pass filters consisting of shunt capacitors, series inductors, or pi-networks store energy during peak conduction and discharge into the load during inter-cycle troughs, drastically reducing ripple factor.'
      ],
      circuit_description: 'Full-wave bridge rectifier schematic with step-down transformer, four 1N4007 diodes, shunt electrolytic filter capacitor, and resistive load RL.',
      working_principle: [
        '1. Positive Half-Cycle: Diodes D1 and D2 are forward-biased, conducting current through load RL from top to bottom.',
        '2. Negative Half-Cycle: Diodes D3 and D4 conduct, maintaining the identical unidirectional current direction through RL.',
        '3. Shunt Capacitor: Charges rapidly to (Vm - 2*Vd) at the voltage crest, then slowly discharges through load with time constant tau = RL * C.',
        '4. Conduction Angle: Diodes conduct current only in brief spikes near peak voltage when input AC exceeds capacitor residual voltage.'
      ],
      equations: [
        {
          title: 'Full-Wave Rectifier Average DC Voltage',
          formula: 'V_{dc} = \\frac{2 V_m}{\\pi} \\approx 0.636 V_m \\quad (\\text{Bridge: } V_{dc} = \\frac{2(V_m - 2V_D)}{\\pi})',
          description: 'Mean DC level across load for an unfiltered sinusoidal input with peak amplitude Vm.'
        },
        {
          title: 'Ripple Factor (gamma)',
          formula: '\\gamma = \\sqrt{\\left(\\frac{V_{rms}}{V_{dc}}\\right)^2 - 1} = 1.21 \\text{ (Half-Wave)}, \\quad 0.482 \\text{ (Full-Wave)}',
          description: 'Measure of AC ripple content relative to DC output voltage.'
        },
        {
          title: 'Capacitor Filter Peak-to-Peak Ripple Voltage',
          formula: 'V_{r(pp)} = \\frac{I_{dc}}{2 f C} = \\frac{V_{dc}}{2 f R_L C}',
          description: 'Peak-to-peak ripple for full-wave rectifier operating at frequency f with filter capacitance C.'
        },
        {
          title: 'Peak Inverse Voltage (PIV)',
          formula: '\\text{PIV}_{Bridge} = V_m, \\quad \\text{PIV}_{Center-Tapped} = 2 V_m',
          description: 'Maximum reverse voltage stress encountered across non-conducting diodes during cycle extremes.'
        }
      ],
      characteristics: [
        {
          title: 'Topology Comparison',
          points: [
            'Half-Wave: Efficiency max 40.6%, Ripple factor 1.21, Fundamental ripple frequency = f',
            'Full-Wave Center-Tapped: Efficiency max 81.2%, Ripple factor 0.482, PIV = 2*Vm, requires bulky transformer',
            'Full-Wave Bridge: Efficiency max 81.2%, Ripple factor 0.482, PIV = Vm, two diode drops in conduction path'
          ]
        }
      ],
      applications: [
        'Linear AC-to-DC laboratory bench power supplies',
        'Offline flyback and SMPS input rectification stages',
        'Automotive alternator 3-phase diode rectification packs',
        'Battery chargers and DC motor drives'
      ],
      advantages: [
        'Full-wave bridge offers highest Transformer Utilization Factor (TUF ~ 0.812)',
        'Doubled ripple frequency (2*f) halves the required smoothing capacitor value',
        'Economical, standard modular bridge packages available up to thousands of amperes'
      ],
      limitations: [
        'Two forward diode drops (2 * 0.7V = 1.4V) in bridge reduce efficiency at low output voltages (e.g. 3.3V or 5V rails)',
        'High repetitive surge current through diodes during capacitor charge pulses',
        'Linear unregulated supplies exhibit poor line and load regulation without active regulators'
      ],
      practical_notes: [
        'Always check the inrush surge rating (IFSM) of diodes against C * (dV/dt) during initial mains turn-on.',
        'Use bleeder resistors across high-voltage filter capacitors to discharge stored lethal charge upon AC disconnection.'
      ]
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  },
  {
    id: 'mod-05',
    course_id: 'c-analog-001',
    title: 'Zener Diode',
    slug: 'zener-diode',
    description: 'Quantum tunneling vs avalanche breakdown mechanisms, Zener impedance, line and load regulation circuits, and temperature coefficient behavior.',
    order_number: 5,
    estimated_minutes: 45,
    content: {
      learning_objectives: [
        'Distinguish between Zener tunneling breakdown (<5V) and Avalanche multiplication breakdown (>6V)',
        'Design a shunt Zener voltage regulator satisfying minimum Izk and maximum Izm constraints',
        'Calculate line regulation (delta Vout / delta Vin) and load regulation (delta Vout / delta Iload)',
        'Account for dynamic Zener resistance (Zz) and zero-temperature-coefficient reference selection at ~5.6V'
      ],
      theory: [
        'A Zener diode is a heavily doped silicon PN junction specifically engineered to operate reliably in its reverse breakdown region without destructive runaway, provided dissipation limits are maintained.',
        'At reverse voltages below ~5V, intense electric fields (>10^6 V/cm) across the extremely thin depletion layer cause valence electrons to tunnel directly into empty conduction states (Zener effect), having a negative temperature coefficient.',
        'At breakdown voltages above ~6V in moderately doped junctions, thermally generated carriers accelerate under the electric field, colliding with lattice atoms to liberate secondary electron-hole pairs (Avalanche breakdown), exhibiting a positive temperature coefficient. Around 5.6V, both coefficients cancel out, creating highly stable voltage references.'
      ],
      circuit_description: 'Zener shunt voltage regulator circuit with series current-limiting resistor Rs, Zener diode Dz, and variable load resistor RL.',
      working_principle: [
        '1. The series resistor Rs drops the excess voltage between fluctuating DC input Vin and regulated output Vz.',
        '2. Total current through Rs divides between Zener diode Iz and load current IL (Is = Iz + IL).',
        '3. When load current decreases, the Zener absorbs the excess current, maintaining its terminal breakdown voltage Vz virtually constant.',
        '4. When input voltage Vin surges, Iz increases, causing increased voltage drop across Rs to preserve constant Vz.'
      ],
      equations: [
        {
          title: 'Series Resistor Selection (Minimum and Maximum Limits)',
          formula: 'R_{s,max} = \\frac{V_{in,min} - V_Z}{I_{L,max} + I_{ZK}}, \\quad R_{s,min} = \\frac{V_{in,max} - V_Z}{I_{L,min} + I_{ZM}}',
          description: 'Where IZK is knee current (minimum for stable regulation) and IZM is maximum safe Zener current (Pmax / VZ).'
        },
        {
          title: 'Line Regulation',
          formula: '\\frac{\\Delta V_o}{\\Delta V_{in}} = \\frac{Z_Z}{R_s + Z_Z} \\approx \\frac{Z_Z}{R_s}',
          description: 'Ratio indicating output voltage stability against input line fluctuations, governed by dynamic Zener impedance ZZ.'
        },
        {
          title: 'Load Regulation',
          formula: '\\frac{\\Delta V_o}{\\Delta I_L} = -(R_s \\parallel Z_Z) \\approx -Z_Z',
          description: 'Output impedance of the shunt regulator dictating voltage drop under increasing output load current.'
        }
      ],
      characteristics: [
        {
          title: 'Breakdown Mechanism Contrast',
          points: [
            'Zener Effect: VZ < 5.1V, Heavily doped, Narrow depletion width, Negative temperature coefficient (voltage decreases with heat)',
            'Avalanche Effect: VZ > 6.2V, Moderately doped, Wider depletion width, Positive temperature coefficient (voltage increases with heat)',
            'Zero Tempco Reference: ~5.6V diode where Zener and Avalanche effects cancel out (~0 mV/°C)'
          ]
        }
      ],
      applications: [
        'Simple low-current DC voltage regulation for microcontroller references',
        'Over-voltage input protection and analog signal clamping',
        'Level-shifting in DC-coupled analog circuits',
        'Precision bandgap voltage reference building blocks'
      ],
      advantages: [
        'Extremely low component count (single diode + single resistor)',
        'Inherent short-circuit protection provided by series current-limiting resistor Rs',
        'Wide choice of standard nominal voltages (e.g. 2.4V, 3.3V, 4.7V, 5.1V, 12V, 15V)'
      ],
      limitations: [
        'Poor efficiency at light loads because surplus current is dissipated as heat in the Zener',
        'Moderate dynamic output impedance (ZZ typically 5 to 30 ohms), limiting precision regulation',
        'Generates wideband microplasma avalanche shot noise requiring parallel bypass capacitor'
      ],
      practical_notes: [
        'Always place a 100nF to 10uF capacitor in parallel with the Zener to quiet avalanche shot noise in audio or ADC references.',
        'Verify that Rs power rating Prs = (Vin,max - Vz)^2 / Rs is derated by at least 2x for high reliability.'
      ]
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  },
  {
    id: 'mod-06',
    course_id: 'c-analog-001',
    title: 'BJT Fundamentals',
    slug: 'bjt-fundamentals',
    description: 'NPN and PNP physics, carrier injection in thin base, alpha and beta current gains, Early effect (base-width modulation), and operational regions.',
    order_number: 6,
    estimated_minutes: 55,
    content: {
      learning_objectives: [
        'Understand physical construction and carrier transport mechanisms in NPN and PNP transistors',
        'Relate alpha (common-base gain) and beta (common-emitter gain) current amplification factors',
        'Identify BJT operating regions: Cutoff, Active (Forward Active), Saturation, and Inverted',
        'Analyze Early effect, Early voltage (VA), and finite output resistance (ro)'
      ],
      theory: [
        'The Bipolar Junction Transistor (BJT) is a three-terminal semiconductor device consisting of two back-to-back PN junctions sharing an ultrathin, lightly doped base layer sandwiched between heavily doped emitter and moderately doped collector regions.',
        'In an NPN transistor biased in Forward Active mode, the Base-Emitter (BE) junction is forward-biased, causing the heavily doped emitter to inject a massive flux of electrons into the thin p-type base. Because the base is narrow and lightly doped, over 98-99% of these electrons diffuse across the base without recombining, where they are swept across the reverse-biased Base-Collector (BC) junction by its strong electric field into the collector.',
        'The collector current is controlled exponentially by the Base-Emitter voltage Vbe (transconductance control) and proportional to base current Ib via current gain beta = Ic / Ib.'
      ],
      circuit_description: 'NPN and PNP circuit symbols with pin terminals (Base, Collector, Emitter), internal electron and hole flux, and output I-V family of curves.',
      working_principle: [
        '1. Cutoff Region: Both BE and BC junctions reverse-biased; collector current Ic is virtually zero (open switch).',
        '2. Forward-Active Region: BE forward-biased (~0.7V), BC reverse-biased; operates as a linear voltage-controlled current source.',
        '3. Saturation Region: Both BE and BC junctions forward-biased; Vce falls to Vce(sat) ~ 0.1V - 0.2V (closed switch).',
        '4. Base-Width Modulation (Early Effect): Increasing reverse bias on BC widens collector-side depletion zone, narrowing effective neutral base width Wb and subtly boosting Ic.'
      ],
      equations: [
        {
          title: 'Collector Current in Forward Active Mode',
          formula: 'I_C = I_S e^{\\frac{V_{BE}}{V_T}} \\left( 1 + \\frac{V_{CE}}{V_A} \\right)',
          description: 'Where Is is transport saturation current, VT is thermal voltage (26mV), and VA is Early voltage.'
        },
        {
          title: 'Current Gain Relations',
          formula: '\\beta = \\frac{\\alpha}{1 - \\alpha}, \\quad \\alpha = \\frac{\\beta}{\\beta + 1}, \\quad I_E = I_C + I_B = (\\beta + 1) I_B',
          description: 'Interrelation between common-base current gain alpha (typically 0.98 - 0.998) and common-emitter current gain beta (50 - 400).'
        },
        {
          title: 'Small-Signal Output Resistance',
          formula: 'r_o = \\frac{V_A + V_{CE}}{I_C} \\approx \\frac{V_A}{I_C}',
          description: 'Incremental output resistance of BJT collector reflecting Early effect slope on IC-VCE curves.'
        }
      ],
      characteristics: [
        {
          title: 'Four Operational Modes',
          points: [
            'Forward Active: BE Forward, BC Reverse -> Linear amplifiers, analog processing',
            'Saturation: BE Forward, BC Forward -> Digital ON state, power switching',
            'Cutoff: BE Reverse, BC Reverse -> Digital OFF state, sub-nanoamp leakage',
            'Reverse Active: BE Reverse, BC Forward -> Low gain inverted mode (rarely intentional)'
          ]
        }
      ],
      applications: [
        'Small-signal audio and RF preamplifiers',
        'Precision current mirrors and active loads',
        'High-speed analog multipliers (Gilbert cells)',
        'Saturated switching drivers for relays and LEDs'
      ],
      advantages: [
        'Superior transconductance per unit current (gm = Ic / VT) compared to MOSFETs',
        'Tight base-emitter threshold matching (Vbe matched to within 1-2 mV in monolithic pairs)',
        'Low 1/f flicker noise, ideal for low-noise audio front-ends'
      ],
      limitations: [
        'Requires non-zero static input base drive current (finite input resistance rpi)',
        'Susceptible to thermal runaway if bias stabilization is neglected',
        'Storage delay time in deep saturation slows down digital switching speed'
      ],
      practical_notes: [
        'Beta varies by up to 3:1 between production batches and increases with temperature; never design circuits relying on exact beta.',
        'Standard silicon NPN transistor: 2N3904 (general purpose), 2N2222A (higher current).'
      ]
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  },
  {
    id: 'mod-07',
    course_id: 'c-analog-001',
    title: 'BJT Biasing',
    slug: 'bjt-biasing',
    description: 'DC operating point (Q-point), DC load line, fixed bias, collector feedback bias, voltage divider bias with emitter degeneration, and stability factor analysis.',
    order_number: 7,
    estimated_minutes: 55,
    content: {
      learning_objectives: [
        'Plot DC load line on output characteristics and establish an optimum mid-point Q-point for maximum symmetric swing',
        'Evaluate thermal runaway and compute stability factors S(Ico), S(Vbe), and S(beta)',
        'Design a robust voltage divider bias network with emitter degeneration resistance RE',
        'Analyze collector feedback biasing as a self-correcting negative feedback topology'
      ],
      theory: [
        'Biasing is the establishment of constant DC voltages and currents in a transistor circuit to set an operating Quiescent Point (Q-point) in the center of the active region, ensuring faithful undistorted amplification of AC signals.',
        'Transistor parameters undergo severe shifts due to temperature changes and manufacturing spreads. Specifically, collector leakage current Ico doubles every 10°C, Vbe decreases by ~2 mV/°C, and current gain beta increases with temperature. In poorly designed circuits, this induces positive thermal feedback leading to destructive thermal runaway.',
        'Voltage divider bias with an emitter resistor RE provides potent negative feedback: any upward surge in collector current increases the emitter voltage drop VE = IE * RE, reducing the net Vbe = VB - VE, which immediately throttles base injection and restores the original Q-point.'
      ],
      circuit_description: 'Universal voltage divider bias network with R1, R2, Rc, RE, and bypass capacitor CE, showing Thevenin equivalent Vth and Rth.',
      working_principle: [
        '1. Base voltage is established by voltage divider: Vth = Vcc * (R2 / (R1 + R2)).',
        '2. Thevenin resistance Rth = R1 || R2 is designed to be much smaller than (beta + 1) * RE so base voltage remains immune to beta shifts.',
        '3. Emitter voltage settles at VE = VB - Vbe ~ VB - 0.7V.',
        '4. Emitter current IE = VE / RE sets collector current IC ~ IE, completely independent of transistor beta.'
      ],
      equations: [
        {
          title: 'Thevenin Equivalent Base Network',
          formula: 'V_{th} = V_{CC} \\left( \\frac{R_2}{R_1 + R_2} \\right), \\quad R_{th} = R_1 \\parallel R_2 = \\frac{R_1 R_2}{R_1 + R_2}',
          description: 'Reduction of voltage divider to a single DC source and series Thevenin resistance.'
        },
        {
          title: 'Emitter Current in Voltage Divider Bias',
          formula: 'I_E = \\frac{V_{th} - V_{BE}}{R_E + \\frac{R_{th}}{\\beta + 1}} \\approx \\frac{V_{th} - V_{BE}}{R_E} \\quad \\text{when } R_{th} \\ll (\\beta + 1) R_E',
          description: 'Governing equation demonstrating beta independence when the strict design rule Rth <= 0.1 * beta * RE is met.'
        },
        {
          title: 'DC Load Line Equation',
          formula: 'V_{CE} = V_{CC} - I_C (R_C + R_E)',
          description: 'Linear relationship between Vce and Ic dictated by external supply rail and load resistors.'
        },
        {
          title: 'Stability Factor S(Ico)',
          formula: 'S = \\frac{1 + \\beta}{1 + \\beta \\left( \\frac{R_E}{R_E + R_{th}} \\right)}',
          description: 'Rate of change of collector current relative to reverse saturation leakage current. Lower values (near 1) indicate superior stability.'
        }
      ],
      characteristics: [
        {
          title: 'Bias Network Comparison',
          points: [
            'Fixed Bias: S = beta + 1 (Extremely poor, highly prone to thermal runaway, unacceptable for production)',
            'Collector Feedback: Moderately stable (S ~ (1+beta) / (1 + beta*(Rc/(Rc+Rb)))), but couples AC output to input',
            'Voltage Divider Bias: Excellent stability (S approaching 1), standard industry best-practice for discrete BJTs'
          ]
        }
      ],
      applications: [
        'Discrete single-stage Class-A audio preamplifiers',
        'Stable transconductance amplifier bias trees',
        'RF front-end gain blocks with constant collector current over temperature',
        'Instrumentation sensor interface buffers'
      ],
      advantages: [
        'Voltage divider bias renders Q-point virtually immune to beta manufacturing tolerance (+-50%)',
        'Prevents thermal runaway over industrial temperature ranges (-40°C to +85°C)',
        'Allows predictable, repeatable mass production without individual potentiometer trimming'
      ],
      limitations: [
        'Unbypassed emitter resistor RE degrades AC voltage gain due to local series negative feedback',
        'Adding bypass capacitor CE restores AC gain but introduces a low-frequency cutoff corner',
        'Divider current draws additional quiescent battery power'
      ],
      practical_notes: [
        'Rule of Thumb for Voltage Divider: Set divider bleed current Ibleed = 10 * Ib, and assign VE ~ 0.1 to 0.2 * Vcc.',
        'For maximum symmetrical output voltage swing, set quiescent Vce = (Vcc - VE) / 2.'
      ]
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  },
  {
    id: 'mod-08',
    course_id: 'c-analog-001',
    title: 'BJT Amplifiers',
    slug: 'bjt-amplifiers',
    description: 'Small-signal hybrid-pi and T models, Common Emitter (CE), Common Base (CB), and Common Collector (CC / Emitter Follower) topologies.',
    order_number: 8,
    estimated_minutes: 60,
    content: {
      learning_objectives: [
        'Derive small-signal parameters gm, rpi, re, and ro from DC quiescent operating point',
        'Analyze Common Emitter (CE) amplifier: voltage gain (Av), input resistance (Rin), and 180° phase inversion',
        'Analyze Common Collector (Emitter Follower): unity voltage gain, high Rin, low Rout buffer performance',
        'Analyze Common Base (CB) amplifier: non-inverting, low Rin, high frequency wideband characteristics'
      ],
      theory: [
        'Under small-signal conditions where AC input amplitude is significantly smaller than thermal voltage VT (e.g. vin < 5-10 mV), the non-linear exponential BJT I-V characteristic is accurately linearized around the DC Q-point using hybrid-pi or T models.',
        'The transconductance gm = Ic / VT represents the slope of collector current relative to base-emitter voltage. The internal base resistance rpi = beta / gm represents AC input resistance looking directly into the base terminal.',
        'The three primary configurations serve complementary roles in signal chains: Common Emitter yields simultaneous high voltage and current gain with phase reversal; Common Collector (Emitter Follower) acts as an impedance-matching buffer; Common Base offers extended high-frequency bandwidth by eliminating the Miller multiplication effect.'
      ],
      circuit_description: 'Small-signal hybrid-pi equivalent circuit model featuring rpi, gm*vbe, and ro, alongside CE amplifier with input/output coupling capacitors and emitter bypass.',
      working_principle: [
        '1. Common Emitter (CE): AC input applied to base, output extracted at collector. Exhibits 180° phase inversion and high voltage gain Av ~ -gm * (Rc || RL).',
        '2. Common Collector (CC): Input at base, output taken from emitter. In-phase voltage gain Av ~ +1, high input impedance, low output impedance ideal for driving low-Z cables or headphones.',
        '3. Common Base (CB): Input at emitter, output at collector, base grounded for AC. No Miller capacitance multiplication, delivering superior ultra-high frequency response.'
      ],
      equations: [
        {
          title: 'Transconductance and Dynamic Base Resistance',
          formula: 'g_m = \\frac{I_C}{V_T}, \\quad r_\\pi = \\frac{\\beta}{g_m} = \\frac{\\beta V_T}{I_C}, \\quad r_e = \\frac{\\alpha}{g_m} \\approx \\frac{V_T}{I_E}',
          description: 'Key small-signal linearized parameters evaluated at room temperature (VT ~ 26mV).'
        },
        {
          title: 'Common Emitter Voltage Gain (Bypassed Emitter)',
          formula: 'A_v = \\frac{v_o}{v_i} = -g_m (R_C \\parallel R_L \\parallel r_o) \\approx -\\frac{R_C \\parallel R_L}{r_e}',
          description: 'Negative sign represents intrinsic 180-degree phase shift between base AC input and collector AC output.'
        },
        {
          title: 'Common Emitter Voltage Gain (Unbypassed Emitter Resistor Re)',
          formula: 'A_v \\approx -\\frac{R_C \\parallel R_L}{R_E + r_e} \\approx -\\frac{R_C}{R_E}',
          description: 'Emitter degeneration stabilizes gain against transistor parameter shifts at the cost of reduced peak gain.'
        },
        {
          title: 'Emitter Follower (CC) Output Resistance',
          formula: 'R_{out} = R_E \\parallel \\left( r_e + \\frac{R_{source} \\parallel R_{th}}{\\beta + 1} \\right)',
          description: 'Low output impedance characteristic that makes emitter followers ideal buffer stages.'
        }
      ],
      characteristics: [
        {
          title: 'BJT Amplifier Topology Comparison',
          points: [
            'Common Emitter: Medium Rin (~1-5 kOhm), High Rout (~Rc), High Voltage Gain (~ -100 to -300), 180° Phase shift',
            'Common Collector: High Rin (tens of kOhm to MOhm), Low Rout (tens of ohms), Voltage Gain ~ 0.99, 0° Phase shift',
            'Common Base: Very Low Rin (~re, 10-50 ohms), High Rout (~Rc), High Voltage Gain (~ +100 to +300), 0° Phase shift'
          ]
        }
      ],
      applications: [
        'Microphone preamplifiers and audio front-ends (CE)',
        'Headphone line drivers and cable-driving output stages (CC / Emitter Follower)',
        'RF cascode amplifier stages and VHF/UHF tuners (CB)',
        'Wideband video amplifiers and active oscilloscope probes'
      ],
      advantages: [
        'Highest voltage-gain-per-stage efficiency among discrete active devices',
        'Predictable gain set by resistor ratios when emitter degeneration is incorporated',
        'Capable of handling wide dynamic range signals with low harmonic distortion'
      ],
      limitations: [
        'Miller effect in CE amplifies base-collector parasitic capacitance Cbc by (1 + |Av|), severely limiting high-frequency bandwidth',
        'Coupling capacitors C1 and C2 restrict low-frequency response (high-pass filtering)',
        'Clipping distortion occurs if AC signal excursion forces transistor into saturation or cutoff'
      ],
      practical_notes: [
        'To bypass RE effectively, ensure capacitor reactance Xc = 1 / (2*pi*f*Ce) is less than 0.1 * RE at lowest operational frequency.',
        'Use cascode configurations (CE driving CB) to eliminate the Miller effect and achieve gigahertz bandwidths.'
      ]
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  },
  {
    id: 'mod-09',
    course_id: 'c-analog-001',
    title: 'FET and MOSFET',
    slug: 'fet-and-mosfet',
    description: 'JFET, Depletion MOSFET, and Enhancement MOSFET; pinch-off voltage, threshold voltage Vth, triode and saturation regions, channel length modulation, and CMOS.',
    order_number: 9,
    estimated_minutes: 55,
    content: {
      learning_objectives: [
        'Explain the operation of JFETs and Enhancement/Depletion MOSFETs',
        'Define threshold voltage (Vth), gate oxide capacitance (Cox), and inversion layer formation',
        'Analyze MOSFET operating regions: Cutoff, Triode (Ohmic/Linear), and Saturation (Active)',
        'Calculate transconductance (gm) and output resistance (ro) with channel length modulation (lambda)'
      ],
      theory: [
        'Field-Effect Transistors (FETs) are unipolar three-terminal devices whose conduction between Source and Drain is modulated by an electrostatic field established across an insulated Gate terminal.',
        'In an n-channel Enhancement-mode MOSFET, the gate is isolated from the p-substrate by an ultra-thin silicon dioxide (SiO2) or high-k dielectric layer. Applying a positive gate-to-source voltage Vgs exceeding the threshold voltage Vth attracts mobile minority electrons to the surface, creating an n-type inversion channel connecting drain and source.',
        'Because the gate is electrostatically insulated, the DC input resistance is virtually infinite (>10^12 ohms), drawing zero steady-state gate current. This property renders MOSFETs the ubiquitous foundation of modern analog and digital VLSI circuits (CMOS).'
      ],
      circuit_description: 'N-channel enhancement MOSFET cross-section, circuit symbol with substrate connection, and output Id-Vds characteristic curves.',
      working_principle: [
        '1. Cutoff Region (Vgs < Vth): No conducting inversion channel exists; drain current Id is essentially zero.',
        '2. Triode/Linear Region (Vgs >= Vth and Vds < Vgs - Vth): Continuous inversion channel behaves as a voltage-controlled resistor.',
        '3. Pinch-Off: When Vds reaches Vds(sat) = Vgs - Vth, the channel depth at the drain pinch-off point reduces to zero.',
        '4. Saturation Region (Vds >= Vgs - Vth): Current saturates into a constant value controlled solely by Vgs, modulo channel length modulation.'
      ],
      equations: [
        {
          title: 'MOSFET Saturation Current (Square-Law)',
          formula: 'I_D = \\frac{1}{2} \\mu_n C_{ox} \\left(\\frac{W}{L}\\right) (V_{GS} - V_{th})^2 (1 + \\lambda V_{DS}) = \\frac{1}{2} k_n\' \\left(\\frac{W}{L}\\right) V_{ov}^2 (1 + \\lambda V_{DS})',
          description: 'Where W/L is aspect ratio, Cox is gate oxide capacitance per unit area, Vov = Vgs - Vth is overdrive voltage, and lambda is channel length modulation coefficient.'
        },
        {
          title: 'MOSFET Triode Region Current',
          formula: 'I_D = \\mu_n C_{ox} \\left(\\frac{W}{L}\\right) \\left[ (V_{GS} - V_{th}) V_{DS} - \\frac{1}{2} V_{DS}^2 \\right]',
          description: 'Current equation valid when Vds < Vgs - Vth, exhibiting variable resistance Ron ~ 1 / [kn * (Vgs - Vth)].'
        },
        {
          title: 'MOSFET Transconductance in Saturation',
          formula: 'g_m = \\frac{\\partial I_D}{\\partial V_{GS}} = \\mu_n C_{ox} \\left(\\frac{W}{L}\\right) (V_{GS} - V_{th}) = \\frac{2 I_D}{V_{GS} - V_{th}} = \\sqrt{2 \\mu_n C_{ox} \\left(\\frac{W}{L}\\right) I_D}',
          description: 'Transconductance varies with the square root of drain current, differing from the linear dependence in BJTs.'
        }
      ],
      characteristics: [
        {
          title: 'MOSFET Key Parameters',
          points: [
            'Overdrive Voltage (Vov): Vov = Vgs - Vth; key design parameter balancing speed and headroom',
            'Channel-Length Modulation: Analogous to BJT Early effect; ro = 1 / (lambda * Id) = VA / Id',
            'Subthreshold Conduction: Weak inversion exponential current flow below Vth, crucial for ultra-low-power biomedical devices'
          ]
        }
      ],
      applications: [
        'CMOS operational amplifiers and analog switches / transmission gates',
        'Power MOSFET switches in buck/boost DC-DC converters',
        'Ultra-high input impedance electrometers and pH sensor probes',
        'Digital logic gates (microprocessors, memories, DSPs)'
      ],
      advantages: [
        'Near-infinite DC input impedance drawing zero static gate bias current',
        'Scalable geometry (W/L ratio directly tailored during IC layout to set gain and current)',
        'Absence of thermal runaway and secondary breakdown phenomena characteristic of power BJTs'
      ],
      limitations: [
        'Gate oxide layer is vulnerable to electrostatic discharge (ESD) punch-through puncture',
        'Lower transconductance gm per milliamp of bias current compared to bipolar transistors',
        'Higher 1/f flicker noise due to carrier trapping at the silicon-oxide interface'
      ],
      practical_notes: [
        'Always connect ESD protection diodes or anti-static wrist straps when handling discrete MOSFETs like 2N7000.',
        'In integrated CMOS design, keep Vov between 150mV and 250mV for balanced voltage gain and output swing.'
      ]
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  },
  {
    id: 'mod-10',
    course_id: 'c-analog-001',
    title: 'Operational Amplifiers',
    slug: 'operational-amplifiers',
    description: 'Ideal vs real op-amp characteristics, open-loop gain, differential input, CMRR, slew rate, input offset voltage, gain-bandwidth product (GBW), and the virtual short concept.',
    order_number: 10,
    estimated_minutes: 60,
    content: {
      learning_objectives: [
        'State ideal op-amp assumptions (Aol = inf, Rin = inf, Rout = 0, CMRR = inf, BW = inf)',
        'Explain the virtual ground / virtual short concept under negative feedback',
        'Quantify Common Mode Rejection Ratio (CMRR) and Power Supply Rejection Ratio (PSRR)',
        'Analyze non-ideal limitations: Slew Rate (SR), Input Offset Voltage (Vos), and Gain-Bandwidth Product (GBW)'
      ],
      theory: [
        'An Operational Amplifier (Op-Amp) is a high-gain, direct-coupled differential voltage amplifier with single-ended output, designed to implement linear and non-linear mathematical operations (addition, subtraction, integration, differentiation).',
        'An ideal op-amp possesses infinite open-loop gain Aol, infinite input impedance, zero output impedance, and infinite bandwidth. When closed within a stable negative feedback loop, the immense open-loop gain drives the differential voltage between inverting (-) and non-inverting (+) inputs to virtually zero volts, creating a "virtual short".',
        'In real op-amps (e.g. LM741, TL072, OPA1612), finite open-loop gain (typically 100dB - 140dB), input offset voltage (microvolts to millivolts), input bias currents, finite slew rate (maximum rate of change of output voltage, dV/dt), and internally compensated dominant-pole rolloff restrict practical high-frequency and large-signal performance.'
      ],
      circuit_description: 'Standard 5-pin op-amp symbol showing non-inverting (+), inverting (-), output, positive supply (V+), and negative supply (V-).',
      working_principle: [
        '1. Differential Stage: Input differential pair amplifies (V+ - V-) while rejecting common-mode noise.',
        '2. Level Shifter / Voltage Gain Stage: Provides massive open-loop voltage amplification (~100,000+).',
        '3. Output Stage: Class-AB push-pull follower provides low output resistance to drive external loads.',
        '4. Negative Feedback Operation: Constrains closed-loop gain strictly by external passive feedback resistors, eliminating dependence on open-loop op-amp variations.'
      ],
      equations: [
        {
          title: 'Ideal Op-Amp Differential Output Relation',
          formula: 'V_o = A_{OL} (V_+ - V_-) \\quad \\implies \\quad V_+ \\approx V_- \\quad \\text{when closed with negative feedback}',
          description: 'Virtual short principle enforced by massive open-loop gain AOL in negative feedback.'
        },
        {
          title: 'Common Mode Rejection Ratio (CMRR)',
          formula: '\\text{CMRR} = 20 \\log_{10} \\left( \\frac{|A_d|}{|A_{cm}|} \\right)',
          description: 'Measure of ability to amplify differential signals while rejecting common-mode noise (typically 80dB to 120dB).'
        },
        {
          title: 'Slew Rate (SR)',
          formula: '\\text{SR} = \\left. \\frac{d V_o}{d t} \\right|_{max} = 2 \\pi f_{max} V_p',
          description: 'Maximum achievable rate of output voltage change, dictating full-power undistorted bandwidth for peak amplitude Vp.'
        },
        {
          title: 'Gain-Bandwidth Product (GBW)',
          formula: '\\text{GBW} = A_{CL} \\cdot f_c = \\text{Constant}',
          description: 'For internally compensated op-amps with single-pole 20 dB/decade rolloff, closed-loop gain multiplied by closed-loop bandwidth is invariant.'
        }
      ],
      characteristics: [
        {
          title: 'Ideal vs Practical (LM741 vs OPAx) Comparison',
          points: [
            'Open-Loop Gain Aol: Ideal = Infinity, LM741 = 200,000 (106 dB), Modern Precision = 2,000,000 (126 dB)',
            'Input Resistance Rin: Ideal = Infinity, LM741 = 2 MOhm, BiFET TL072 = 10^12 Ohm (1 TOhm)',
            'Output Resistance Rout: Ideal = 0 Ohm, LM741 = 75 Ohm (open loop), near 0 closed loop',
            'Slew Rate: Ideal = Infinity, LM741 = 0.5 V/us, Audio OPAs = 20-50 V/us, High-speed = >1000 V/us'
          ]
        }
      ],
      applications: [
        'Instrumentation amplifiers for thermocouple and strain-gauge sensors',
        'Audio active equalization filters and preamplifiers',
        'Analog-to-digital converter (ADC) driver and anti-aliasing buffers',
        'Precision current sources and voltage references'
      ],
      advantages: [
        'Closed-loop circuit properties determined purely by external resistors and capacitors',
        'Extremely high input impedance prevents loading of sensitive preceding stages',
        'Broad standard product availability from general purpose to sub-microvolt precision'
      ],
      limitations: [
        'Output voltage cannot swing beyond DC supply rails (rail-to-rail op-amps approach within millivolts)',
        'Internally compensated dominant pole limits full gain to frequencies below ~10 Hz to 100 Hz',
        'Oscillation occurs if excessive capacitive loading introduces phase lag into negative feedback path'
      ],
      practical_notes: [
        'Never leave unused op-amp inputs floating; configure spare sections as voltage followers with non-inverting input tied to a mid-rail bias voltage.',
        'Always place 100nF ceramic bypass capacitors within 5mm of the op-amp power pins to prevent parasitic high-frequency oscillations.'
      ]
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  },
  {
    id: 'mod-11',
    course_id: 'c-analog-001',
    title: 'Op-Amp Applications',
    slug: 'op-amp-applications',
    description: 'Inverting and non-inverting amplifiers, voltage follower (buffer), summing amplifier, difference amplifier, active integrator, differentiator, and instrumentation amplifier.',
    order_number: 11,
    estimated_minutes: 65,
    content: {
      learning_objectives: [
        'Analyze inverting and non-inverting closed-loop amplifier gains using virtual ground concepts',
        'Design precision summing amplifiers and difference (differential) subtraction circuits',
        'Construct active integrators and differentiators with practical frequency stabilization resistors',
        'Synthesize 3-op-amp instrumentation amplifiers with high input impedance and superior CMRR'
      ],
      theory: [
        'Negative feedback configured around an operational amplifier permits accurate, predictable realization of fundamental mathematical and analog signal processing functions.',
        'The Inverting Amplifier feeds the output back through Rf to the inverting input while the non-inverting terminal is tied to ground, creating a virtual ground at the summing junction. The closed-loop gain is simply Av = -Rf / R1, with input impedance equal to R1.',
        'The Non-Inverting Amplifier applies the input directly to the non-inverting terminal, yielding infinite input impedance and positive gain Av = 1 + (Rf / R1). Setting Rf = 0 and R1 = inf yields the unity-gain Voltage Follower buffer.',
        'Replacing resistors with reactive capacitive elements transforms the circuit into an Active Integrator (output proportional to time integral of input) or Differentiator. Adding a shunt resistor in parallel with the integrator capacitor prevents DC drift saturation caused by input offset voltages.'
      ],
      circuit_description: 'Classic 3-Op-Amp Instrumentation Amplifier schematic featuring two non-inverting input buffer stages with variable gain resistor Rgain driving a difference stage.',
      working_principle: [
        '1. Inverting Summing Amplifier: Currents from multiple input channels sum algebraically at the virtual ground node without mutual channel interaction.',
        '2. Difference Amplifier: Subtracts two analog voltages Vo = (Rf / R1) * (V2 - V1), provided resistor matching ratios (Rf/R1 = R4/R3) are precisely adhered to.',
        '3. Active Integrator: Constant input DC voltage generates a constant current into feedback capacitor C, causing output voltage to ramp linearly: Vo(t) = -1/(R*C) * integral(Vi dt).',
        '4. Instrumentation Amplifier: Input buffer stage amplifies only differential signals while presenting unity gain to common mode, delivering CMRR exceeding 100 dB.'
      ],
      equations: [
        {
          title: 'Inverting & Non-Inverting Closed-Loop Gains',
          formula: 'A_{v,inv} = -\\frac{R_f}{R_1}, \\quad A_{v,non-inv} = 1 + \\frac{R_f}{R_1}',
          description: 'Fundamental closed-loop voltage gains determined entirely by resistor feedback ratios.'
        },
        {
          title: 'Active Integrator Output Voltage',
          formula: 'v_o(t) = -\\frac{1}{R C} \\int_0^t v_i(\\tau) d\\tau + v_o(0)',
          description: 'Continuous mathematical integration in the time domain, corresponding to -20 dB/decade frequency rolloff.'
        },
        {
          title: 'Three-Op-Amp Instrumentation Amplifier Gain',
          formula: 'A_d = \\left( 1 + \\frac{2 R_1}{R_{gain}} \\right) \\left( \\frac{R_4}{R_3} \\right)',
          description: 'Overall differential voltage gain where Rgain allows single-resistor gain adjustment without compromising resistor network balance.'
        }
      ],
      characteristics: [
        {
          title: 'Circuit Selection Rules',
          points: [
            'Voltage Follower (Buffer): Av = 1, Rin = 10^12 Ohm, Rout < 0.1 Ohm; separates high-impedance sensors from low-impedance loads',
            'Summing Amplifier: Virtual ground prevents crosstalk between input signal channels',
            'Practical Differentiator: Requires series input resistor and feedback capacitor to suppress high-frequency noise and maintain phase margin'
          ]
        }
      ],
      applications: [
        'Sensor signal conditioning (strain gauges, thermocouples, load cells)',
        'Audio mixing consoles (virtual ground summing nodes)',
        'Analog computing and PID analog feedback controllers',
        'Waveform generation (square-to-triangle wave integrators)'
      ],
      advantages: [
        'Gain can be set with 0.1% precision using standard precision metal-film resistors',
        'Virtual ground prevents interactions between multiple incoming signal lines in summing amplifiers',
        'Zero output impedance ensures driving capacity into subsequent stages'
      ],
      limitations: [
        'Pure differentiators are inherently noisy and prone to high-frequency oscillation due to phase lag',
        'Integrators will drift into rail saturation if input DC offset voltage is not compensated',
        'Common-mode rejection in single op-amp difference amplifier degrades quickly if external resistor tolerances exceed 0.1%'
      ],
      practical_notes: [
        'Always connect a resistor Rfb in parallel with the feedback capacitor in an integrator (set Rshunt ~ 10 * R) to provide DC feedback and prevent output saturation.',
        'To minimize offset voltage errors due to input bias currents, add a compensation resistor Rcomp = R1 || Rf at the non-inverting terminal.'
      ]
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  },
  {
    id: 'mod-12',
    course_id: 'c-analog-001',
    title: 'Feedback Amplifiers',
    slug: 'feedback-amplifiers',
    description: 'Negative vs positive feedback, feedback topologies (voltage-series, voltage-shunt, current-series, current-shunt), desensitization, bandwidth extension, and stability.',
    order_number: 12,
    estimated_minutes: 55,
    content: {
      learning_objectives: [
        'Understand the Black feedback model: Open-loop gain (A), feedback factor (beta), and loop gain (A*beta)',
        'Classify the four feedback topologies based on input mixing and output sampling mechanisms',
        'Demonstrate benefits of negative feedback: gain desensitization, bandwidth expansion, distortion reduction, and noise reduction',
        'Evaluate effects of feedback on input and output impedances for each topology'
      ],
      theory: [
        'Feedback is the process where a fraction beta of the output signal is returned to the input port and combined algebraically with the incoming reference signal. When the returned signal subtracts from the input (180° out of phase), Negative Feedback is established.',
        'Harold Black invented negative feedback in 1927 to conquer distortion in transcontinental telephone repeaters. While negative feedback reduces overall closed-loop gain Af = A / (1 + A*beta) by the amount of the desensitization factor D = (1 + A*beta), it stabilizes the gain against component variations by the exact same factor.',
        'Negative feedback dramatically extends -3dB bandwidth, lowers non-linear harmonic distortion, suppresses power supply ripple, and allows exact tailoring of input and output impedances to suit voltage, current, transconductance, or transimpedance amplification requirements.'
      ],
      circuit_description: 'General feedback block diagram illustrating summer node, forward open-loop amplifier A(s), feedback network beta(s), and error signal ve.',
      working_principle: [
        '1. Sampling: The output is sampled either as a voltage (parallel/shunt connection across load) or as a current (series connection with load).',
        '2. Feedback Transmission: Network beta extracts fraction of sampled variable and conveys it to the input.',
        '3. Mixing: Returned signal is mixed at the input either as a voltage (series subtraction) or as a current (shunt subtraction).',
        '4. Stabilization: Any perturbation in output generates an opposing correction in error signal ve = vs - vf, stabilizing the system.'
      ],
      equations: [
        {
          title: 'Closed-Loop Gain with Negative Feedback',
          formula: 'A_f = \\frac{A}{1 + A \\beta} \\approx \\frac{1}{\\beta} \\quad \\text{when } A \\beta \\gg 1',
          description: 'Demonstrates that closed-loop gain Af becomes entirely independent of forward amplifier gain A when loop gain A*beta is large.'
        },
        {
          title: 'Gain Sensitivity / Desensitization',
          formula: '\\frac{d A_f}{A_f} = \\frac{1}{1 + A \\beta} \\left( \\frac{d A}{A} \\right)',
          description: 'Fractional change in closed-loop gain is reduced by desensitization factor (1 + A*beta) relative to open-loop shifts.'
        },
        {
          title: 'Bandwidth Extension',
          formula: 'f_{H,f} = f_H (1 + A_0 \\beta), \\quad f_{L,f} = \\frac{f_L}{1 + A_0 \\beta}',
          description: 'Negative feedback broadens high-frequency cutoff while lowering low-frequency cutoff, preserving constant gain-bandwidth product.'
        }
      ],
      characteristics: [
        {
          title: 'Four Feedback Topologies & Impedance Effects',
          points: [
            'Voltage-Series (Series-Shunt): Senses Voltage, Mixes Voltage -> Rin increases by (1+A*beta), Rout decreases by (1+A*beta) -> Ideal Voltage Amplifier',
            'Current-Series (Series-Series): Senses Current, Mixes Voltage -> Rin increases by (1+A*beta), Rout increases by (1+A*beta) -> Ideal Transconductance Amplifier',
            'Voltage-Shunt (Shunt-Shunt): Senses Voltage, Mixes Current -> Rin decreases by (1+A*beta), Rout decreases by (1+A*beta) -> Ideal Transimpedance Amplifier',
            'Current-Shunt (Shunt-Series): Senses Current, Mixes Current -> Rin decreases by (1+A*beta), Rout increases by (1+A*beta) -> Ideal Current Amplifier'
          ]
        }
      ],
      applications: [
        'High-fidelity audio power amplifiers with ultra-low THD (<0.001%)',
        'Regulated linear low-dropout (LDO) DC power supply feedback loops',
        'Photodiode transimpedance amplifiers in fiber-optic communications',
        'Precision automated industrial servomechanisms and motor control'
      ],
      advantages: [
        'Gain stabilization against temperature, aging, and transistor parameter spreads',
        'Drastic reduction of non-linear distortion produced by large-signal active devices',
        'Expansion of usable operating frequency bandwidth'
      ],
      limitations: [
        'Direct loss of voltage or current gain (gain is traded off directly for bandwidth and linearity)',
        'Risk of instability and spontaneous oscillation if phase shifts approach 180° at high frequencies',
        'Feedback cannot reduce noise or distortion generated in the initial input stage'
      ],
      practical_notes: [
        'To guarantee closed-loop stability, ensure phase margin exceeds 45° (preferably 60°) where loop gain |A*beta| crosses 0 dB (unity gain).',
        'Use Bode plots and Nyquist criteria during AC simulation to verify adequate gain and phase margins.'
      ]
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  },
  {
    id: 'mod-13',
    course_id: 'c-analog-001',
    title: 'Oscillators',
    slug: 'oscillators',
    description: 'Barkhausen criterion, RC phase-shift oscillator, Wien bridge oscillator, Hartley and Colpitts LC oscillators, crystal oscillators, and frequency stability.',
    order_number: 13,
    estimated_minutes: 60,
    content: {
      learning_objectives: [
        'Formulate Barkhausen criteria for sustained sinusoidal oscillations (|A*beta| = 1, total phase shift = 0° or 360°)',
        'Analyze RC Phase-Shift oscillators using three cascaded RC lead/lag sections',
        'Design Wien Bridge oscillators with automatic gain control (AGC) amplitude stabilization',
        'Compare Hartley (tapped inductor) and Colpitts (tapped capacitor) high-frequency LC topologies',
        'Evaluate quartz crystal piezoelectric resonators and ultra-high Q frequency stability'
      ],
      theory: [
        'An electronic oscillator is an autonomous circuit that converts direct current (DC) energy into a continuous, periodic alternating current (AC) waveform without an external AC input signal.',
        'According to the Barkhausen criterion, sustained sinusoidal oscillation requires two conditions at the oscillation frequency fo: the magnitude of the loop gain must equal unity (|A*beta| = 1), and the total phase shift around the closed loop must be an integer multiple of 360° (or 0°).',
        'At startup, circuit noise or the turn-on DC surge provides initial infinitesimal thermal noise across all frequencies. The selective feedback network filters out all components except fo, which meets the 0° phase condition. By designing initial small-signal loop gain slightly greater than unity (|A*beta| > 1), the oscillation grows exponentially until non-linear gain compression or active AGC limits the amplitude to a stable, steady-state limit cycle.'
      ],
      circuit_description: 'Wien Bridge oscillator schematic with non-inverting op-amp, series and parallel RC frequency selective branches, and tungsten lamp/JFET AGC.',
      working_principle: [
        '1. Startup: Thermal noise voltages at non-inverting input are amplified by closed-loop gain A.',
        '2. Frequency Selection: The reactive feedback network (RC or LC) introduces exact 0° phase shift at only one specific resonance frequency fo.',
        '3. Wien Bridge: At resonance fo = 1 / (2*pi*R*C), the bridge feedback ratio is exactly beta = 1/3 with zero phase angle. Amplifier gain must equal Av = 1 + (Rf / R1) = 3.',
        '4. Amplitude Limiting: Back-to-back Zener diodes, thermistors, or JFET channel resistors gently throttle amplifier gain down to exactly 3 as amplitude expands, preventing harmonic clipping.'
      ],
      equations: [
        {
          title: 'Barkhausen Criterion for Oscillation',
          formula: '|A(j\\omega_0) \\beta(j\\omega_0)| = 1 \\quad \\text{and} \\quad \\angle A(j\\omega_0) \\beta(j\\omega_0) = 0^\\circ \\text{ or } 2\\pi n',
          description: 'Condition of unity loop gain magnitude and zero net phase shift around the closed feedback loop.'
        },
        {
          title: 'Wien Bridge Resonance Frequency',
          formula: 'f_0 = \\frac{1}{2 \\pi R C}, \\quad \\beta = \\frac{1}{3} \\implies A_v = 3 \\quad \\left( \\frac{R_f}{R_1} = 2 \\right)',
          description: 'Center frequency and required minimum amplifier gain for symmetrical Wien bridge components.'
        },
        {
          title: 'RC Phase-Shift Oscillator Frequency',
          formula: 'f_0 = \\frac{1}{2 \\pi R C \\sqrt{6}} \\quad (\\text{BJT: } f_0 = \\frac{1}{2 \\pi R C \\sqrt{6 + 4(R_C/R)}}), \\quad |A_v| \\ge 29',
          description: 'Three 60-degree RC stages yield 180-degree phase shift, combined with 180-degree inverting amplifier phase shift.'
        },
        {
          title: 'Colpitts LC Oscillator Frequency',
          formula: 'f_0 = \\frac{1}{2 \\pi \\sqrt{L C_{eq}}}, \\quad C_{eq} = \\frac{C_1 C_2}{C_1 + C_2}',
          description: 'Resonant frequency determined by inductor L and series combination of split capacitors C1 and C2.'
        }
      ],
      characteristics: [
        {
          title: 'Oscillator Topologies by Frequency Spectrum',
          points: [
            'RC Phase-Shift: Low to medium audio frequencies (10 Hz - 100 kHz); bulky capacitors at sub-audio frequencies',
            'Wien Bridge: Standard low-distortion laboratory sine generator (1 Hz - 1 MHz); excellent sine purity',
            'Colpitts & Hartley LC: High frequency RF and communications (1 MHz - 500 MHz); high spectral purity',
            'Quartz Crystal: Ultra-high stability (Q factors from 10,000 to 1,000,000); ppm frequency tolerance'
          ]
        }
      ],
      applications: [
        'Clock signal generation for microcontrollers and digital processors',
        'Local oscillators in radio receivers (heterodyne mixing)',
        'Function generators and laboratory test synthesis equipment',
        'Ultrasonic transducers and sonar transmitters'
      ],
      advantages: [
        'Produces clean, autonomous periodic sinusoidal or square AC signals from pure DC power rails',
        'Quartz crystal oscillators deliver frequency drift under 10 parts-per-million (ppm) over temperature',
        'Colpitts LC oscillator circuits are easy to tune electronically using varactor diodes'
      ],
      limitations: [
        'Without active AGC, oscillators tend to clip into power supply rails, generating heavy harmonic distortion',
        'Component heating causes frequency drift (df/dT) in inductors and capacitors',
        'LC oscillators require high-Q inductors which are costly and physically bulky at audio frequencies'
      ],
      practical_notes: [
        'Always design the initial loop gain at startup to be 1.2x to 1.5x the minimum Barkhausen value to guarantee reliable start up across cold temperatures.',
        'Use NP0/C0G dielectric ceramic capacitors in oscillator resonant tanks to prevent thermal frequency drift.'
      ]
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  },
  {
    id: 'mod-14',
    course_id: 'c-analog-001',
    title: 'Power Amplifiers',
    slug: 'power-amplifiers',
    description: 'Large-signal operation, Class A, Class B push-pull, crossover distortion, Class AB biasing, Class C, Class D switching amplifiers, thermal resistance, and heatsinks.',
    order_number: 14,
    estimated_minutes: 60,
    content: {
      learning_objectives: [
        'Distinguish small-signal voltage amplifiers from large-signal power amplifiers',
        'Compare conduction angle, maximum theoretical collector efficiency, and distortion across Classes A, B, AB, C, and D',
        'Analyze crossover distortion in Class B complementary push-pull stages and resolve it using Class AB diode biasing',
        'Calculate thermal junction temperature (Tj), thermal resistance (theta_ja), and heatsink sizing requirements'
      ],
      theory: [
        'Power amplifiers are large-signal output stages engineered to deliver substantial electrical power (watts to kilowatts) into low-impedance loads (e.g. 4-8 ohm loudspeakers, RF transmission antennas, or motor windings) with acceptable efficiency and minimal harmonic distortion.',
        'In Class A amplifiers, the transistor conducts over the full 360° of the AC input cycle. While offering highest linearity, continuous static bias current results in a dismal maximum theoretical efficiency of only 25% (50% with transformer coupling), turning most power into waste heat.',
        'Class B uses complementary push-pull pairs (NPN and PNP) where each device conducts for exactly 180° of the cycle, raising theoretical efficiency to 78.5%. However, near zero-crossing, both transistors turn off because base-emitter voltages drop below 0.7V, producing severe crossover distortion.',
        'Class AB solves crossover distortion by pre-biasing both transistors slightly above cutoff with diodes or Vbe multipliers. Class D amplifiers operate transistors purely as switching switches at high PWM frequencies, attaining efficiencies exceeding 90%.'
      ],
      circuit_description: 'Complementary Class AB push-pull output stage with NPN/PNP output transistors, Vbe multiplier bias spreader, emitter ballasting resistors, and 8-ohm speaker load.',
      working_principle: [
        '1. Positive Half-Cycle: Input swings positive; upper NPN transistor conducts, sourcing current from Vcc into the load.',
        '2. Negative Half-Cycle: Input swings negative; lower PNP transistor conducts, sinking current from load into -Vee.',
        '3. Class AB Diodes: Two forward-biased diodes (or Vbe multiplier) maintain ~1.4V between the bases of the NPN and PNP devices, ensuring smooth conduction handoff and zero crossover dead-zone.',
        '4. Thermal Tracking: Bias diodes are mounted on the same heatsink as the power transistors so that heating reduces diode voltage, preventing thermal runaway.'
      ],
      equations: [
        {
          title: 'Maximum Theoretical Efficiencies',
          formula: '\\eta_{Class\\,A} = 25\\% \\text{ (Direct)}, \\, 50\\% \\text{ (Transformer)}; \\quad \\eta_{Class\\,B/AB} = \\frac{\\pi}{4} \\approx 78.5\\%; \\quad \\eta_{Class\\,D} > 90\\%',
          description: 'Ratio of maximum achievable AC load power to total DC power consumed from power supply rails.'
        },
        {
          title: 'Class B Push-Pull Output Power and Dissipation',
          formula: 'P_{L,max} = \\frac{V_{CC}^2}{2 R_L}, \\quad P_{D,max} = \\frac{2 V_{CC}^2}{\\pi^2 R_L} \\approx 0.203 \\frac{V_{CC}^2}{R_L}',
          description: 'Maximum power delivered to load and maximum internal power dissipation occurring at Vpeak = (2/pi) * Vcc.'
        },
        {
          title: 'Thermal Resistance and Junction Temperature',
          formula: 'T_J = T_A + P_D (\\theta_{JC} + \\theta_{CS} + \\theta_{SA}) \\le T_{J,max}',
          description: 'Junction temperature calculated from ambient temperature TA, dissipated power PD, and junction-to-case, case-to-sink, and sink-to-ambient thermal resistances.'
        }
      ],
      characteristics: [
        {
          title: 'Amplifier Class Operating Parameters',
          points: [
            'Class A: Conduction angle 360°, Zero crossover distortion, Poor efficiency (max 25-50%), Heavy heatsinking required',
            'Class B: Conduction angle 180°, Severe crossover distortion, Max efficiency 78.5%, Low idling quiescent power',
            'Class AB: Conduction angle slightly > 180°, Negligible crossover distortion, Efficiency 50-70%, Standard for linear audio',
            'Class C: Conduction angle < 180°, Highly non-linear, High efficiency (~85%), Used in tuned RF power stages',
            'Class D: Conduction angle 0°/360° (Switching PWM), Efficiency > 90-95%, Minimal heatsink, Compact form factor'
          ]
        }
      ],
      applications: [
        'Professional audio stage power amplifiers and active subwoofers',
        'Cellular base station RF transmitters and broadcast antennas',
        'Brushless DC motor drivers and robotics actuators',
        'Magnetic resonance imaging (MRI) gradient power amplifiers'
      ],
      advantages: [
        'Class AB delivers audiophile-grade high-fidelity linearity with acceptable thermal efficiency',
        'Class D permits battery-powered portable Bluetooth speakers to run for 20+ hours on single charge',
        'Push-pull topology naturally cancels even-order harmonic distortion components'
      ],
      limitations: [
        'High continuous power dissipation requires heavy extruded aluminum heatsinks and forced-air cooling fans',
        'Vulnerable to thermal runaway if emitter degeneration ballasting resistors are omitted',
        'Class D requires careful electromagnetic shielding and LC output reconstruction filtering to prevent high-frequency EMI radiation'
      ],
      practical_notes: [
        'Always include low-value (0.22 to 0.47 ohm, 5W) ceramic emitter ballasting resistors in push-pull stages to equalize current sharing and stabilize against thermal runaway.',
        'Apply thermal grease (silicone paste) between transistor TO-220/TO-247 packages and the heatsink to lower theta_CS.'
      ]
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  },
  {
    id: 'mod-15',
    course_id: 'c-analog-001',
    title: 'Final Assessment',
    slug: 'final-assessment',
    description: 'Comprehensive 30-question final examination covering all 14 modules. 30 minutes duration. 70% passing threshold for accredited digital certificate generation.',
    order_number: 15,
    estimated_minutes: 30,
    content: {
      learning_objectives: [
        'Synthesize holistic understanding across discrete semiconductor devices, integrated circuits, and analog systems',
        'Solve multi-stage analog circuit design problems under timed examination conditions',
        'Demonstrate proficiency in calculation of gains, impedances, cutoff frequencies, and efficiencies',
        'Attain a minimum passing score of 70% (21/30 correct) to earn accredited CircuitIQ certification'
      ],
      theory: [
        'The Final Assessment serves as the culmination of your journey through the Analog Electronic Circuits curriculum on CircuitIQ.',
        'This 30-question comprehensive evaluation samples questions proportionally from every fundamental subject area: semiconductor carrier physics, PN diodes, rectifiers, Zener regulators, BJT small-signal models and biasing, FETs and MOSFETs, operational amplifier mathematics, feedback topologies, oscillators, and power stages.',
        'You have exactly 30 minutes to complete the assessment. The questions are randomized. A score of 70% or higher unlocks an immutable, digitally verified CircuitIQ Certificate of Completion with a verifiable cryptographic QR code and unique certificate ID.'
      ],
      circuit_description: 'CircuitIQ Analog Electronics Certification schematic summarizing the complete analog signal processing pipeline from sensor transducer to power output stage.',
      working_principle: [
        '1. Ensure you have reviewed all 14 module quizzes and theoretical equations prior to initiating.',
        '2. Once initiated, the 30-minute countdown timer operates continuously.',
        '3. Select an answer (A, B, C, or D) for each question. You can freely navigate between questions before final submission.',
        '4. Upon submission, your score is calculated immediately. Scores >= 70% trigger automatic server-side PDF certificate creation, unique certificate number generation, and instant verification availability.'
      ],
      equations: [
        {
          title: 'Final Assessment Passing Criteria',
          formula: '\\text{Score} = \\left( \\frac{\\text{Correct Answers}}{30} \\right) \\times 100\\% \\ge 70.00\\% \\quad (\\ge 21 / 30)',
          description: 'Strict passing threshold required for issuance of verified credentials.'
        }
      ],
      characteristics: [
        {
          title: 'Exam Rules & Protocol',
          points: [
            'Total Questions: 30 multiple-choice questions (4 options per question)',
            'Duration: 30 minutes continuous countdown',
            'Passing Mark: 70% (21 correct responses)',
            'Retakes: Retakes permitted if candidate does not achieve 70% threshold'
          ]
        }
      ],
      applications: [
        'Academic credit validation for undergraduate electrical engineering coursework',
        'Professional engineering portfolio verification and LinkedIn certification credentials',
        'Readiness certification for analog IC design and hardware engineering roles'
      ],
      advantages: [
        'Provides definitive, objective verification of analog engineering mastery',
        'Generates print-ready high-resolution PDF certificate with embedded public QR verification link',
        'Permanent record in CircuitIQ public verification database'
      ],
      limitations: [
        'Timed assessment requires prompt time management (averaging 1 minute per question)',
        'Unanswered questions at timer expiration will be scored as incorrect'
      ],
      practical_notes: [
        'Have a scientific calculator, scratch paper, and pen ready before starting the timer.',
        'Review high-weight equations: diode voltage temperature coefficient, gm = Ic/VT, non-inverting op-amp gain, and oscillator resonant frequencies.'
      ]
    },
    created_at: '2026-01-15T00:00:00Z',
    updated_at: '2026-09-29T12:00:00Z'
  }
];
