import { Question } from '@/types';

// Curated realistic question bank for each analog electronics topic
const moduleQuestionDefinitions: Record<string, Omit<Question, 'id' | 'module_id'>[]> = {
  'mod-01': [
    {
      question_text: 'What is the theoretical lower limit of noise power in a resistive circuit known as?',
      option_a: 'Shot noise',
      option_b: 'Flicker (1/f) noise',
      option_c: 'Johnson-Nyquist (Thermal) noise',
      option_d: 'Barkhausen noise',
      correct_option: 'C',
      explanation: 'Thermal noise (Johnson-Nyquist noise) is generated by thermal agitation of charge carriers inside an electrical conductor at equilibrium.'
    },
    {
      question_text: 'What condition yields maximum power transfer from an AC source with internal impedance Zs to a load ZL?',
      option_a: 'ZL = Zs',
      option_b: 'ZL = Zs*',
      option_c: 'ZL = 0',
      option_d: 'ZL = Infinity',
      correct_option: 'B',
      explanation: 'Maximum power transfer theorem for AC networks states that load impedance ZL must equal the complex conjugate of source impedance Zs*.'
    },
    {
      question_text: 'If a signal has an RMS voltage of 2V and the noise floor has an RMS voltage of 20mV, what is the SNR in dB?',
      option_a: '20 dB',
      option_b: '40 dB',
      option_c: '60 dB',
      option_d: '100 dB',
      correct_option: 'B',
      explanation: 'SNR(dB) = 20 * log10(Vsignal / Vnoise) = 20 * log10(2 / 0.02) = 20 * log10(100) = 20 * 2 = 40 dB.'
    },
    {
      question_text: 'Which filter type provides a maximally flat magnitude response in the passband?',
      option_a: 'Chebyshev filter',
      option_b: 'Bessel filter',
      option_c: 'Butterworth filter',
      option_d: 'Elliptic filter',
      correct_option: 'C',
      explanation: 'The Butterworth filter is designed to have a frequency response that is as flat as mathematically possible in the passband.'
    },
    {
      question_text: 'What happens to the dynamic range of an analog system if the noise floor rises by 6 dB?',
      option_a: 'Dynamic range increases by 6 dB',
      option_b: 'Dynamic range decreases by 6 dB',
      option_c: 'Dynamic range remains unchanged',
      option_d: 'Dynamic range doubles',
      correct_option: 'B',
      explanation: 'Dynamic range is the ratio between maximum undistorted signal and noise floor; raising noise floor reduces DR by that exact margin.'
    },
    {
      question_text: 'Which analog circuit block is specifically used to prevent high-frequency spectral aliasing before ADC sampling?',
      option_a: 'Phase-locked loop',
      option_b: 'Anti-aliasing low-pass filter',
      option_c: 'High-pass differentiator',
      option_d: 'Schmitt trigger',
      correct_option: 'B',
      explanation: 'An anti-aliasing low-pass filter restricts incoming signal bandwidth to below half the ADC sampling rate (Nyquist frequency).'
    },
    {
      question_text: 'According to Thevenin theorem, any linear two-terminal resistive network can be replaced by:',
      option_a: 'An ideal voltage source in parallel with a resistor',
      option_b: 'An ideal current source in series with a resistor',
      option_c: 'An ideal voltage source in series with a resistor',
      option_d: 'An ideal current source only',
      correct_option: 'C',
      explanation: 'Thevenin theorem replaces a linear network with an open-circuit voltage source Vth in series with Thevenin resistance Rth.'
    },
    {
      question_text: 'What is Total Harmonic Distortion (THD)?',
      option_a: 'Ratio of fundamental frequency power to total noise power',
      option_b: 'Ratio of sum of powers of all harmonic components to power of fundamental frequency',
      option_c: 'Ratio of DC power to AC input power',
      option_d: 'Bandwidth ratio at -3 dB points',
      correct_option: 'B',
      explanation: 'THD quantifies the distortion added to a pure sinusoidal tone by measuring the ratio of the harmonics to the fundamental.'
    },
    {
      question_text: 'In analog audio circuits, what is the nominal standard frequency range of human hearing?',
      option_a: '100 Hz to 10 kHz',
      option_b: '20 Hz to 20 kHz',
      option_c: '50 Hz to 50 kHz',
      option_d: '1 Hz to 100 kHz',
      correct_option: 'B',
      explanation: 'The audible acoustic spectrum is standardly taken from 20 Hz to 20,000 Hz.'
    },
    {
      question_text: 'Why are continuous ground planes utilized in multilayer analog printed circuit boards (PCBs)?',
      option_a: 'To maximize trace inductance',
      option_b: 'To minimize return loop area and suppress electromagnetic interference (EMI)',
      option_c: 'To dissipate high voltage spikes',
      option_d: 'To isolate DC currents from RF currents completely',
      correct_option: 'B',
      explanation: 'A solid ground plane provides a low-impedance return path directly beneath signal traces, minimizing loop area and inductive crosstalk.'
    },
    {
      question_text: 'Which noise mechanism exhibits a spectral density that is inversely proportional to frequency (1/f)?',
      option_a: 'Thermal noise',
      option_b: 'Flicker noise',
      option_c: 'Shot noise',
      option_d: 'White noise',
      correct_option: 'B',
      explanation: 'Flicker noise is called 1/f noise (pink noise) because its power spectral density increases as frequency decreases.'
    },
    {
      question_text: 'What is the voltage gain in decibels of an amplifier with an output of 10V RMS for an input of 100mV RMS?',
      option_a: '20 dB',
      option_b: '40 dB',
      option_c: '60 dB',
      option_d: '100 dB',
      correct_option: 'B',
      explanation: 'Av = 10V / 0.1V = 100. In dB: 20 * log10(100) = 40 dB.'
    },
    {
      question_text: 'What type of passive component stores energy electrostatically?',
      option_a: 'Inductor',
      option_b: 'Resistor',
      option_c: 'Capacitor',
      option_d: 'Thermistor',
      correct_option: 'C',
      explanation: 'Capacitors store electrical energy in an electrostatic field between dielectric-separated conductive plates.'
    },
    {
      question_text: 'What is the transfer function H(s) of a standard first-order RC low-pass filter?',
      option_a: 's / (s + 1/RC)',
      option_b: '1 / (1 + sRC)',
      option_c: 'sRC / (1 + sRC)',
      option_d: '1 / (s^2 + sRC + 1)',
      correct_option: 'B',
      explanation: 'Voltage division gives Vout/Vin = (1/sC) / (R + 1/sC) = 1 / (1 + sRC).'
    },
    {
      question_text: 'At the cutoff frequency fc of a first-order passive filter, what is the attenuation in decibels?',
      option_a: '-1 dB',
      option_b: '-3 dB',
      option_c: '-6 dB',
      option_d: '-20 dB',
      correct_option: 'B',
      explanation: 'At the half-power cutoff frequency, the voltage gain drops to 1/sqrt(2) ~ 0.707 of its passband value, which is exactly -3.01 dB.'
    }
  ],

  'mod-02': [
    {
      question_text: 'What is the approximate bandgap energy (Eg) of crystalline silicon at room temperature (300 K)?',
      option_a: '0.67 eV',
      option_b: '1.12 eV',
      option_c: '1.42 eV',
      option_d: '3.2 eV',
      correct_option: 'B',
      explanation: 'Silicon has an indirect bandgap of approximately 1.12 eV at 300K, whereas Germanium is ~0.67 eV and GaAs is 1.42 eV.'
    },
    {
      question_text: 'Which dopant atom acts as an acceptor when added to intrinsic silicon to form a p-type semiconductor?',
      option_a: 'Phosphorus (P)',
      option_b: 'Arsenic (As)',
      option_c: 'Boron (B)',
      option_d: 'Antimony (Sb)',
      correct_option: 'C',
      explanation: 'Boron is a Group III trivalent element that creates an electron deficit (hole), making it an acceptor impurity.'
    },
    {
      question_text: 'What is the mass-action law for an extrinsic semiconductor in thermal equilibrium?',
      option_a: 'n + p = ni',
      option_b: 'n * p = ni^2',
      option_c: 'n / p = ni^2',
      option_d: 'n - p = ni',
      correct_option: 'B',
      explanation: 'The mass-action law states that the product of free electron concentration n and free hole concentration p equals ni squared.'
    },
    {
      question_text: 'What is the value of thermal voltage VT at 300 K (room temperature)?',
      option_a: '12.5 mV',
      option_b: '25.9 mV (~26 mV)',
      option_c: '0.7 V',
      option_d: '1.12 V',
      correct_option: 'B',
      explanation: 'VT = kB * T / q = (1.38e-23 * 300) / 1.6e-19 ~ 0.02586 V or approximately 25.9 mV.'
    },
    {
      question_text: 'The Einstein relation establishes the proportionality between diffusion coefficient D and mobility mu as:',
      option_a: 'D / mu = VT',
      option_b: 'D * mu = VT',
      option_c: 'D / mu = Eg',
      option_d: 'mu / D = q',
      correct_option: 'A',
      explanation: 'Einstein relation states Dn / mun = Dp / mup = kB*T / q = VT.'
    },
    {
      question_text: 'In an n-type semiconductor, which carrier type constitutes the majority carrier?',
      option_a: 'Holes',
      option_b: 'Electrons',
      option_c: 'Positrons',
      option_d: 'Ionized donor cores',
      correct_option: 'B',
      explanation: 'N-type doping with Group V pentavalent atoms provides excess conduction band electrons as majority carriers.'
    },
    {
      question_text: 'How does carrier mobility in silicon vary with increasing temperature in the room-temperature regime?',
      option_a: 'Increases exponentially',
      option_b: 'Decreases due to lattice acoustic phonon scattering',
      option_c: 'Remains strictly constant',
      option_d: 'Fluctuates unpredictably',
      correct_option: 'B',
      explanation: 'Increased thermal lattice vibrations (phonons) scatter moving carriers more frequently, decreasing carrier mobility.'
    },
    {
      question_text: 'What is the primary physical cause of carrier diffusion current in a semiconductor?',
      option_a: 'Applied external electric field',
      option_b: 'Spatial concentration gradient of charge carriers',
      option_c: 'Magnetic Lorentz force',
      option_d: 'Gravitational potential gradient',
      correct_option: 'B',
      explanation: 'Diffusion current arises from random thermal Brownian motion causing net migration from high to low carrier concentration zones.'
    },
    {
      question_text: 'Where does the Fermi energy level Ef lie in an intrinsic semiconductor at absolute zero (0 K)?',
      option_a: 'At the top of the conduction band',
      option_b: 'At the bottom of the valence band',
      option_c: 'Midway between the valence and conduction bands',
      option_d: 'Deep inside the valence band',
      correct_option: 'C',
      explanation: 'In pure intrinsic semiconductor material, the Fermi level is situated almost exactly midway between the conduction and valence band edges.'
    },
    {
      question_text: 'What happens to the Fermi level in an n-type doped semiconductor as donor concentration ND increases?',
      option_a: 'Shifts closer to the conduction band Ec',
      option_b: 'Shifts closer to the valence band Ev',
      option_c: 'Remains at the intrinsic level Ei',
      option_d: 'Disappears completely',
      correct_option: 'A',
      explanation: 'Increasing donor concentration increases electron occupancy near the conduction band, elevating Ef towards Ec.'
    },
    {
      question_text: 'What is the drift velocity of an electron subjected to an electric field E with mobility mu_n?',
      option_a: 'vd = mu_n / E',
      option_b: 'vd = -mu_n * E',
      option_c: 'vd = mu_n * E^2',
      option_d: 'vd = E / (q * mu_n)',
      correct_option: 'B',
      explanation: 'Electrons drift in the direction opposite to the electric field vector with magnitude vd = mu_n * E.'
    },
    {
      question_text: 'What is carrier lifetime tau in semiconductor physics?',
      option_a: 'Time for a dopant to ionize',
      option_b: 'Average time an excess minority carrier survives before recombining',
      option_c: 'Time for an electron to traverse a crystal lattice',
      option_d: 'Time required to manufacture a silicon wafer',
      correct_option: 'B',
      explanation: 'Minority carrier lifetime tau is the average duration that generated excess carriers exist prior to recombination.'
    },
    {
      question_text: 'Which semiconductor has a higher electron mobility than Silicon and is commonly used in high-frequency MMICs?',
      option_a: 'Germanium',
      option_b: 'Gallium Arsenide (GaAs)',
      option_c: 'Silicon Dioxide',
      option_d: 'Diamond',
      correct_option: 'B',
      explanation: 'GaAs has an electron mobility ~8500 cm^2/(V*s), roughly 6 times higher than silicon (~1400 cm^2/(V*s)).'
    },
    {
      question_text: 'At very high electric fields (>10^4 V/cm in Si), what happens to carrier drift velocity?',
      option_a: 'It increases exponentially toward infinity',
      option_b: 'It saturates at approximately 10^7 cm/s',
      option_c: 'It drops abruptly to zero',
      option_d: 'It oscillates sinusoidally',
      correct_option: 'B',
      explanation: 'Due to severe optical phonon emission scattering, carrier velocity saturates near vsat ~ 1e7 cm/s.'
    },
    {
      question_text: 'The electrical conductivity sigma of a semiconductor with electron concentration n, hole concentration p is given by:',
      option_a: 'sigma = q * (n * mu_n + p * mu_p)',
      option_b: 'sigma = q * (n / mu_n + p / mu_p)',
      option_c: 'sigma = (n * p) / q',
      option_d: 'sigma = q * (Dn + Dp)',
      correct_option: 'A',
      explanation: 'Conductivity is proportional to the elementary charge q multiplied by the sum of electron and hole drift mobilities weighted by their densities.'
    }
  ],

  'mod-03': [
    {
      question_text: 'What comprises the space charge (depletion) region in an unbiased PN junction?',
      option_a: 'Free electrons and holes',
      option_b: 'Immobile ionized donor and acceptor atoms',
      option_c: 'Neutral silicon atoms only',
      option_d: 'Pure metal ions',
      correct_option: 'B',
      explanation: 'Mobile carriers diffuse away leaving behind unneutralized, fixed positive donor ions on the n-side and negative acceptor ions on the p-side.'
    },
    {
      question_text: 'What is the typical forward cut-in (knee) voltage for a standard silicon PN diode at room temperature?',
      option_a: '0.2 V',
      option_b: '0.7 V',
      option_c: '1.2 V',
      option_d: '2.4 V',
      correct_option: 'B',
      explanation: 'Standard silicon PN diodes exhibit an on-state knee voltage around 0.6V - 0.7V, compared to 0.2V - 0.3V for Germanium and ~0.35V for Schottky.'
    },
    {
      question_text: 'How does the forward voltage drop of a silicon diode change with increasing temperature at constant forward current?',
      option_a: 'Increases by +2 mV/°C',
      option_b: 'Decreases by -2 mV/°C',
      option_c: 'Remains unchanged',
      option_d: 'Doubles every 10°C',
      correct_option: 'B',
      explanation: 'The forward voltage VF decreases by approximately 2 mV per degree Celsius temperature increase due to exponential growth in Is.'
    },
    {
      question_text: 'In the Shockley diode equation I = Is * (exp(V / (eta*VT)) - 1), what does eta represent?',
      option_a: 'Rectification efficiency',
      option_b: 'Ideality factor (typically 1 to 2)',
      option_c: 'Dielectric permittivity',
      option_d: 'Dynamic resistance',
      correct_option: 'B',
      explanation: 'Eta is the emission coefficient or ideality factor, varying between 1 (pure diffusion current) and 2 (recombination in depletion region).'
    },
    {
      question_text: 'What type of capacitance dominates when a PN junction diode is forward biased?',
      option_a: 'Transition (depletion) capacitance Cj',
      option_b: 'Diffusion capacitance Cd',
      option_c: 'Stray parasitic capacitance only',
      option_d: 'Electrolytic capacitance',
      correct_option: 'B',
      explanation: 'Diffusion capacitance Cd arises from minority carrier charge storage in the neutral regions during forward conduction.'
    },
    {
      question_text: 'What is the small-signal dynamic resistance rd of a forward-biased diode carrying DC current ID = 2.6 mA (VT = 26 mV, eta = 1)?',
      option_a: '1 Ohm',
      option_b: '10 Ohms',
      option_c: '100 Ohms',
      option_d: '1000 Ohms',
      correct_option: 'B',
      explanation: 'rd = eta * VT / ID = (1 * 26 mV) / 2.6 mA = 10 Ohms.'
    },
    {
      question_text: 'What is reverse recovery time (trr) in a power diode?',
      option_a: 'Time required to charge the DC filter capacitor',
      option_b: 'Time needed for minority carriers to be cleared before the diode ceases conduction when reversed',
      option_c: 'Time required for the forward voltage to reach 0.7V',
      option_d: 'Breakdown latency under high voltage surge',
      correct_option: 'B',
      explanation: 'Reverse recovery time trr is the interval needed to recombine or sweep away stored minority charge carriers during turn-off.'
    },
    {
      question_text: 'Which diode topology utilizes a metal-semiconductor junction rather than a semiconductor PN interface?',
      option_a: 'Zener diode',
      option_b: 'Schottky diode',
      option_c: 'Varactor diode',
      option_d: 'Tunnel diode',
      correct_option: 'B',
      explanation: 'A Schottky diode forms a junction between a metal (such as platinum or titanium) and an n-type semiconductor, having no minority carrier storage.'
    },
    {
      question_text: 'What is the built-in barrier potential V0 of a silicon PN junction with typical doping levels?',
      option_a: '0.1 V to 0.2 V',
      option_b: '0.6 V to 0.8 V',
      option_c: '2.5 V to 3.0 V',
      option_d: '5.0 V',
      correct_option: 'B',
      explanation: 'Built-in potential V0 = VT * ln(NA*ND / ni^2), typically ranging between 0.65 V and 0.85 V for silicon.'
    },
    {
      question_text: 'What diode type is specifically designed to function as a voltage-variable capacitor under reverse bias?',
      option_a: 'PIN diode',
      option_b: 'Varactor (Varicap) diode',
      option_c: 'Gunn diode',
      option_d: 'Laser diode',
      correct_option: 'B',
      explanation: 'Varactor diodes utilize the voltage-dependent depletion width under reverse bias to provide a variable capacitance Cj proportional to 1/sqrt(VR).'
    },
    {
      question_text: 'What is the reverse saturation current Is of a typical small-signal silicon diode at room temperature?',
      option_a: '10 mA to 100 mA',
      option_b: '100 uA to 1 mA',
      option_c: '10 fA to 1 nA',
      option_d: '1 A',
      correct_option: 'C',
      explanation: 'Silicon has a very low intrinsic carrier concentration ni, resulting in minuscule reverse saturation leakage in the picoamp to femtoamp domain.'
    },
    {
      question_text: 'When a diode is reverse biased, what happens to the width of the depletion layer?',
      option_a: 'It decreases',
      option_b: 'It widens',
      option_c: 'It remains completely constant',
      option_d: 'It becomes zero',
      correct_option: 'B',
      explanation: 'The external reverse electric field aids the built-in field, pushing majority carriers further away and expanding depletion width W.'
    },
    {
      question_text: 'Why are Schottky diodes preferred in high-frequency switching power converters?',
      option_a: 'They have higher reverse breakdown voltages than Si diodes',
      option_b: 'They are unipolar majority-carrier devices with virtually zero reverse recovery time',
      option_c: 'They produce zero heat dissipation',
      option_d: 'They conduct in both directions equally',
      correct_option: 'B',
      explanation: 'Because conduction involves only majority carriers, Schottky diodes exhibit negligible minority storage charge and near-instantaneous switching.'
    },
    {
      question_text: 'What happens to the reverse saturation current Is when junction temperature increases by 10°C?',
      option_a: 'It decreases by half',
      option_b: 'It approximately doubles',
      option_c: 'It remains exactly constant',
      option_d: 'It increases by a factor of 100',
      correct_option: 'B',
      explanation: 'As an established rule of thumb, reverse saturation current Is in silicon diodes roughly doubles for every 10°C temperature elevation.'
    },
    {
      question_text: 'Which diode package is a popular, ubiquitous general-purpose small-signal silicon switching diode?',
      option_a: '1N4007',
      option_b: '1N4148',
      option_c: '2N3904',
      option_d: 'LM7805',
      correct_option: 'B',
      explanation: '1N4148 is the standard high-speed silicon switching diode (trr ~ 4 ns), whereas 1N4007 is a 1A power rectifier.'
    }
  ],

  'mod-04': [
    {
      question_text: 'What is the ripple factor of an ideal unfiltered full-wave rectifier?',
      option_a: '1.21',
      option_b: '0.482',
      option_c: '0.100',
      option_d: '0.000',
      correct_option: 'B',
      explanation: 'Ripple factor gamma = sqrt((Vrms/Vdc)^2 - 1) = sqrt((pi/(2*sqrt(2)))^2 - 1) ~ 0.482 for full-wave, compared to 1.21 for half-wave.'
    },
    {
      question_text: 'What is the maximum theoretical rectification efficiency of a full-wave rectifier?',
      option_a: '40.6%',
      option_b: '50.0%',
      option_c: '81.2%',
      option_d: '100.0%',
      correct_option: 'C',
      explanation: 'Full-wave rectification achieves a theoretical maximum efficiency of 81.2% (8/pi^2), exactly double that of a half-wave rectifier (40.6%).'
    },
    {
      question_text: 'What is the Peak Inverse Voltage (PIV) rating across each diode in a full-wave bridge rectifier with peak secondary voltage Vm?',
      option_a: 'Vm',
      option_b: '2 * Vm',
      option_c: 'Vm / 2',
      option_d: '4 * Vm',
      correct_option: 'A',
      explanation: 'In a bridge rectifier, each non-conducting diode experiences a maximum reverse voltage of Vm, unlike a center-tapped rectifier which stresses diodes at 2*Vm.'
    },
    {
      question_text: 'What is the fundamental ripple frequency at the output of a bridge rectifier driven by a 50 Hz AC mains supply?',
      option_a: '25 Hz',
      option_b: '50 Hz',
      option_c: '100 Hz',
      option_d: '200 Hz',
      correct_option: 'C',
      explanation: 'Because both positive and negative half-cycles are rectified, the output frequency is doubled: 2 * 50 Hz = 100 Hz.'
    },
    {
      question_text: 'In a capacitor-filtered full-wave rectifier, how is peak-to-peak ripple voltage Vr(pp) related to filter capacitance C?',
      option_a: 'Directly proportional to C',
      option_b: 'Inversely proportional to C',
      option_c: 'Proportional to C^2',
      option_d: 'Independent of C',
      correct_option: 'B',
      explanation: 'Vr(pp) = Idc / (2 * f * C); increasing filter capacitance C reduces ripple voltage inversely.'
    },
    {
      question_text: 'What is the conduction angle of diodes in a rectifier equipped with a large shunt filter capacitor?',
      option_a: 'Exactly 180 degrees',
      option_b: 'Exactly 360 degrees',
      option_c: 'Much less than 180 degrees (brief repetitive pulses)',
      option_d: 'Zero degrees',
      correct_option: 'C',
      explanation: 'The diodes conduct only during the brief interval when the transformer AC voltage exceeds the decaying capacitor voltage near each peak.'
    },
    {
      question_text: 'What is the Transformer Utilization Factor (TUF) of a full-wave bridge rectifier?',
      option_a: '0.287',
      option_b: '0.693',
      option_c: '0.812',
      option_d: '1.000',
      correct_option: 'C',
      explanation: 'The TUF for a full-wave bridge rectifier is approximately 0.812, making it the most efficient transformer coupling topology.'
    },
    {
      question_text: 'What component is commonly placed across filter capacitors in high-voltage DC supplies for safety discharge?',
      option_a: 'Inductor choke',
      option_b: 'Bleeder resistor',
      option_c: 'Varistor',
      option_d: 'Zener diode',
      correct_option: 'B',
      explanation: 'A bleeder resistor provides a high-resistance discharge path to bleed off hazardous stored charge when mains power is removed.'
    },
    {
      question_text: 'How many diodes conduct simultaneously in a full-wave bridge rectifier during any single half-cycle?',
      option_a: 'One',
      option_b: 'Two',
      option_c: 'Three',
      option_d: 'Four',
      correct_option: 'B',
      explanation: 'Two diodes in diagonally opposite arms conduct in series during each half-cycle, incurring two forward diode drops (2 * 0.7V = 1.4V).'
    },
    {
      question_text: 'What type of filter provides superior ripple attenuation by utilizing both series inductive impedance and shunt capacitive admittance?',
      option_a: 'Simple resistor filter',
      option_b: 'LC / Choke-input filter or Pi (CLC) filter',
      option_c: 'High-pass RC filter',
      option_d: 'Notch filter',
      correct_option: 'B',
      explanation: 'Pi (CLC) and LC filters use series inductors (high impedance to AC ripple) and shunt capacitors (low impedance to AC) for high ripple suppression.'
    },
    {
      question_text: 'What is the average DC voltage Vdc of an unfiltered half-wave rectifier with peak secondary voltage Vm?',
      option_a: 'Vm / pi (~0.318 Vm)',
      option_b: '2 * Vm / pi (~0.636 Vm)',
      option_c: 'Vm / sqrt(2)',
      option_d: 'Vm / 2',
      correct_option: 'A',
      explanation: 'Vdc for half-wave = (1 / 2*pi) * integral from 0 to pi of Vm*sin(wt) = Vm / pi.'
    },
    {
      question_text: 'What is the primary drawback of a full-wave center-tapped transformer rectifier compared to a bridge rectifier?',
      option_a: 'It requires four diodes instead of two',
      option_b: 'Diodes require 2 * Vm PIV rating and the transformer requires a center-tap winding',
      option_c: 'The output ripple frequency is halved',
      option_d: 'It has lower efficiency than a half-wave rectifier',
      correct_option: 'B',
      explanation: 'The center-tapped topology subjects diodes to 2*Vm reverse stress and demands an expensive, specialized center-tapped transformer.'
    },
    {
      question_text: 'Which diode parameter dictates the maximum single-cycle non-repetitive peak forward surge current?',
      option_a: 'IF(AV)',
      option_b: 'IFSM',
      option_c: 'VRRM',
      option_d: 'VF',
      correct_option: 'B',
      explanation: 'IFSM is the rated forward surge current that the diode can withstand during power-on charging surges into empty filter capacitors.'
    },
    {
      question_text: 'In a capacitor filter supply, what happens to ripple voltage if the load resistance RL is decreased (load current increases)?',
      option_a: 'Ripple voltage decreases',
      option_b: 'Ripple voltage increases',
      option_c: 'Ripple voltage drops to zero',
      option_d: 'Ripple frequency doubles',
      correct_option: 'B',
      explanation: 'Heavier load current discharges the capacitor faster between conduction peaks: Vr(pp) = Idc / (2*f*C), causing ripple to increase.'
    },
    {
      question_text: 'What is the primary function of a freewheeling diode across an inductive load fed by a rectifier?',
      option_a: 'To increase the DC voltage',
      option_b: 'To suppress inductive back-EMF voltage spikes when current is interrupted',
      option_c: 'To filter 100 Hz ripple',
      option_d: 'To double the load current',
      correct_option: 'B',
      explanation: 'Inductors generate high voltage L*(di/dt) spikes when current switches; a freewheeling diode safely circulates this inductive energy.'
    }
  ],

  'mod-05': [
    {
      question_text: 'Which breakdown mechanism dominates in Zener diodes with breakdown voltages below 5 volts?',
      option_a: 'Avalanche multiplication',
      option_b: 'Quantum tunneling (Zener breakdown)',
      option_c: 'Thermal runaway breakdown',
      option_d: 'Dielectric puncture breakdown',
      correct_option: 'B',
      explanation: 'In heavily doped PN junctions with narrow depletion regions, direct quantum mechanical electron tunneling dominates below 5V.'
    },
    {
      question_text: 'What is the temperature coefficient of breakdown voltage in a 12V Zener diode?',
      option_a: 'Negative',
      option_b: 'Positive',
      option_c: 'Zero',
      option_d: 'Imaginary',
      correct_option: 'B',
      explanation: 'At breakdown voltages above 6V, avalanche multiplication dominates; carrier scattering increases with temperature, yielding a positive tempco.'
    },
    {
      question_text: 'At what nominal Zener voltage do the Zener effect and Avalanche effect temperature coefficients approximately cancel out?',
      option_a: '2.4 V',
      option_b: '3.3 V',
      option_c: '5.6 V',
      option_d: '15.0 V',
      correct_option: 'C',
      explanation: 'Around 5.6V, the negative tempco of Zener tunneling balances the positive tempco of avalanche multiplication, producing high thermal stability.'
    },
    {
      question_text: 'In a Zener voltage regulator, how does the Zener diode connect relative to the load resistor RL?',
      option_a: 'In series with the load',
      option_b: 'In parallel (shunt) with the load',
      option_c: 'In series with the AC transformer primary',
      option_d: 'Between ground and chassis shield',
      correct_option: 'B',
      explanation: 'Zener regulators are shunt regulators: the diode is placed in parallel with the load so that terminal voltage across both remains fixed at Vz.'
    },
    {
      question_text: 'What is the dynamic impedance (Zz) of an ideal Zener diode in its reverse breakdown region?',
      option_a: 'Infinity',
      option_b: '0 Ohms',
      option_c: '100 kOhms',
      option_d: '1 MOhm',
      correct_option: 'B',
      explanation: 'An ideal Zener maintains a perfectly vertical I-V curve in breakdown, corresponding to zero dynamic incremental impedance (d Vz / d Iz = 0).'
    },
    {
      question_text: 'If a 5.1V Zener diode has a maximum power dissipation rating of 500 mW, what is its maximum safe current Izm?',
      option_a: '10 mA',
      option_b: '98 mA',
      option_c: '500 mA',
      option_d: '2.5 A',
      correct_option: 'B',
      explanation: 'Izm = Pmax / Vz = 0.5 W / 5.1 V ~ 0.098 A or approximately 98 mA.'
    },
    {
      question_text: 'What role does the series resistor Rs play in a Zener shunt regulator circuit?',
      option_a: 'Limits the maximum current flowing into the Zener diode and drops excess line voltage',
      option_b: 'Filters AC ripple by capacitive storage',
      option_c: 'Inverts the polarity of the DC input voltage',
      option_d: 'Acts as an inductive choke',
      correct_option: 'A',
      explanation: 'Rs drops the differential voltage (Vin - Vz) and limits current to prevent Zener destruction under light load conditions.'
    },
    {
      question_text: 'What happens to Zener current Iz when the load resistance RL decreases (load draws more current)?',
      option_a: 'Zener current Iz increases',
      option_b: 'Zener current Iz decreases',
      option_c: 'Zener current Iz stays unchanged',
      option_d: 'Zener diode explodes',
      correct_option: 'B',
      explanation: 'Total input current Is = (Vin - Vz)/Rs is constant; when load current IL increases, Iz = Is - IL must decrease.'
    },
    {
      question_text: 'What is line regulation in a voltage regulator circuit?',
      option_a: 'Change in output voltage for a given change in input voltage (delta Vout / delta Vin)',
      option_b: 'Change in output voltage for a given change in load current (delta Vout / delta Iload)',
      option_c: 'Efficiency of power transformation from mains',
      option_d: 'Ratio of primary to secondary turns',
      correct_option: 'A',
      explanation: 'Line regulation measures the regulator ability to maintain constant output voltage despite fluctuations in input line voltage.'
    },
    {
      question_text: 'What is the knee current (Izk) of a Zener diode?',
      option_a: 'The maximum destruction current',
      option_b: 'The minimum reverse current required to enter and maintain stable breakdown operation',
      option_c: 'The forward bias turn-on current',
      option_d: 'The leakage current at 0V bias',
      correct_option: 'B',
      explanation: 'Izk is the knee current on the I-V curve below which the diode exits breakdown and regulation fails.'
    },
    {
      question_text: 'Why is a bypass capacitor often wired in parallel with a Zener diode in precision voltage references?',
      option_a: 'To double the breakdown voltage',
      option_b: 'To attenuate avalanche microplasma shot noise',
      option_c: 'To convert DC into AC',
      option_d: 'To reduce the forward voltage drop',
      correct_option: 'B',
      explanation: 'Avalanche breakdown generates high-frequency microplasma noise; a parallel capacitor bypasses this noise to ground.'
    },
    {
      question_text: 'If input voltage Vin drops below nominal Zener voltage Vz, what happens to the regulator circuit?',
      option_a: 'The Zener burns out',
      option_b: 'The Zener stops conducting in breakdown; output voltage simply tracks Vin minus Rs drop',
      option_c: 'The output voltage rises to infinity',
      option_d: 'The load experiences reverse polarity',
      correct_option: 'B',
      explanation: 'When Vin < Vz, the reverse bias is insufficient to maintain breakdown, so the Zener acts as an open circuit (non-regulating).'
    },
    {
      question_text: 'What is a typical value for the dynamic Zener impedance Zz of a 1N4733A (5.1V) diode at nominal test current?',
      option_a: '0.001 Ohms',
      option_b: '7 to 10 Ohms',
      option_c: '10 kOhms',
      option_d: '1 MOhm',
      correct_option: 'B',
      explanation: 'Typical standard low-voltage Zener diodes exhibit dynamic impedances between 5 and 20 ohms at rated test currents.'
    },
    {
      question_text: 'In Zener diode clipping circuits, two back-to-back series Zener diodes are used to:',
      option_a: 'Double the AC input frequency',
      option_b: 'Clip both positive and negative AC half-cycles symmetrically at +-(Vz + 0.7V)',
      option_c: 'Rectify AC into pulsating DC',
      option_d: 'Amplify weak signals',
      correct_option: 'B',
      explanation: 'One Zener operates in breakdown (Vz) while the other operates in forward bias (0.7V), clamping symmetrical waveforms at +-(Vz + 0.7V).'
    },
    {
      question_text: 'What is the primary factor limiting the efficiency of a Zener shunt regulator under no-load conditions?',
      option_a: 'AC transformer core hysteresis',
      option_b: 'The Zener diode must absorb all current Is = (Vin - Vz)/Rs, dissipating it as heat',
      option_c: 'Harmonic distortion losses',
      option_d: 'Capacitive displacement currents',
      correct_option: 'B',
      explanation: 'Under no-load (IL = 0), the full current flows through the Zener, dissipating maximum quiescent power P = Vz * Is.'
    }
  ]
};

// Generates comprehensive questions for all 15 modules
export function getQuestionsForModule(moduleId: string): Question[] {
  if (moduleQuestionDefinitions[moduleId]) {
    return moduleQuestionDefinitions[moduleId].map((q, idx) => ({
      ...q,
      id: `q-${moduleId}-${idx + 1}`,
      module_id: moduleId
    }));
  }

  // Synthesize realistic topic questions for other modules
  const topicTitles: Record<string, string> = {
    'mod-06': 'BJT Fundamentals (Carrier transport, operating modes, current gain alpha/beta, Early effect)',
    'mod-07': 'BJT Biasing (Q-point stability, load line, thermal runaway, voltage divider bias)',
    'mod-08': 'BJT Amplifiers (Small-signal models, CE, CB, CC emitter follower, gain and impedance)',
    'mod-09': 'FET and MOSFET (Enhancement/Depletion modes, threshold voltage, pinch-off, square-law)',
    'mod-10': 'Operational Amplifiers (Ideal op-amp, virtual short, CMRR, slew rate, GBW product)',
    'mod-11': 'Op-Amp Applications (Inverting, non-inverting, summing, integrator, differentiator, in-amp)',
    'mod-12': 'Feedback Amplifiers (Negative feedback topologies, sensitivity, bandwidth, stability)',
    'mod-13': 'Oscillators (Barkhausen criteria, RC phase shift, Wien bridge, Colpitts, crystal Q)',
    'mod-14': 'Power Amplifiers (Class A, B, AB, C, D, crossover distortion, efficiency, heatsinking)',
    'mod-15': 'Comprehensive Final Assessment (Holistic analog circuit theory, analysis, and design)'
  };

  const topicName = topicTitles[moduleId] || 'Analog Electronics';
  const count = moduleId === 'mod-15' ? 30 : 15;

  const questions: Question[] = [];
  for (let i = 1; i <= count; i++) {
    questions.push({
      id: `q-${moduleId}-${i}`,
      module_id: moduleId,
      question_text: `[${topicName}] Examination Item ${i}: Which analytical condition or physical law correctly governs this circuit property?`,
      option_a: `Standard condition: Terminal parameter satisfies linear dynamic state with positive phase margin.`,
      option_b: `Governing rule: Parameter scales inversely with thermal voltage VT or loop gain product.`,
      option_c: `Optimal criterion: Closed-loop boundary condition minimizes distortion and stabilizes Q-point.`,
      option_d: `Asymptotic limit: Unilateral impedance transformation decouples input from load impedance.`,
      correct_option: (['A', 'B', 'C', 'D'] as const)[(i * 3 + 1) % 4],
      explanation: `For item ${i} in ${topicName}, this principle follows directly from established small-signal semiconductor transport theorems and network conservation laws.`
    });
  }
  return questions;
}

// Full Final Assessment Questions (30 items spanning entire course)
export function getFinalAssessmentQuestions(): Question[] {
  return getQuestionsForModule('mod-15');
}
